using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Web.SessionState;
using System.Web.UI.HtmlControls;
using System.Web.UI.DataVisualization.Charting;
using CRM.DataAccess.Dashboard;
using CRM.Core.Constants;
using CRM.Model.Security;
using CRM.DataAccess;
using System.Text;
using System.Data.SqlClient;
using System.Data.Sql;
using System.Configuration;


namespace CRM.WebApp.Views.Charts.Account
{
    public partial class ExpenseBreakDown : System.Web.UI.UserControl
    {
        private int _userID;
        AuthorizationBDto objAuthorizationBDto;
        deshboardentity objdeshboardentity = new deshboardentity();
        //AuthorizationBDto objAuthorizationBDto;
        //deshboardentity objdeshboardentity = new deshboardentity();
        string str = ConfigurationManager.ConnectionStrings["CRM"].ToString();
        protected void Page_Load(object sender, EventArgs e)
        {
            WebHelper.WebManager.CheckSessionIsActive();
            objAuthorizationBDto = (AuthorizationBDto)Session[PageConstants.ssnUserAuthorization];
            if (objAuthorizationBDto != null)

                _userID = objAuthorizationBDto.UserProfile.UserId;
            Series series = new Series("Pie");
            series.ChartType = SeriesChartType.Pie;
            series.BorderWidth = 1;
            series.ShadowOffset = 2;


            DataSet _Ds = objdeshboardentity.getfilter(_userID);
            DataTable _DT = _Ds.Tables[0];
            DataTable _DT1 = _Ds.Tables[1];
            //GET FILTER DETAILS FROM HERE
            string query = string.Empty;
            StringBuilder _employee = new StringBuilder();
            if (_DT.Rows[0]["EMP_ID"].ToString() == null || _DT.Rows[0]["EMP_ID"].ToString() == "0" || _DT.Rows[0]["EMP_ID"].ToString() == "")
            {
                foreach (DataRow dr in _DT1.Rows)
                {
                    _employee.Append(dr["EMP_ID"].ToString() + ",");
                }
                _employee.Append("0");
            }
            else
            {
                foreach (DataRow dr in _DT1.Rows)
                {
                    if (dr["RESULT"].ToString() == _DT.Rows[0]["EMP_ID"].ToString())
                        _employee.Append(dr["EMP_ID"].ToString() + ",");
                }
                _employee.Append("0");

            }

             switch (_DT.Rows[0]["FILTER_ID"].ToString())
            {
                case "12":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '5' AND CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) = CONVERT(VARCHAR(15),GETDATE(), 103) GROUP BY CONVERT (VARCHAR(15),PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE,103),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND CONVERT (VARCHAR(15), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 103) = CONVERT(VARCHAR(15),GETDATE(), 103) GROUP BY CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) , EXPENCE_VOUCHER_DETAILS.GL_CODE UNION ALL SELECT SUM(PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_AMOUNT) AS  TOTAL_EXPENCE_AMOUNT, CONVERT (VARCHAR(15), PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE, 103 ) AS YEAR ,    CHART_OF_ACCOUNTS.GL_DESCRIPTION AS SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_HEADER LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_DETAILS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO = PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO AND PURCHASE_PAYMENT_VOUCHER_DETAILS.CR_AMOUNT  = '0.00' LEFT OUTER JOIN CHART_OF_ACCOUNTS ON CHART_OF_ACCOUNTS.GL_CODE = PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE WHERE PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '11' AND CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE), 103) = CONVERT(VARCHAR(15),GETDATE(), 103) GROUP BY CONVERT (VARCHAR(15),  PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE ,103) , CHART_OF_ACCOUNTS.GL_DESCRIPTION ORDER BY YEAR";
                    break;
                case "13":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '5' AND CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) = CONVERT(VARCHAR(15),GETDATE()-1 , 103) GROUP BY CONVERT (VARCHAR(15),PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE,103),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND CONVERT (VARCHAR(15), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 103) = CONVERT(VARCHAR(15),GETDATE() -1 , 103) GROUP BY CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) , EXPENCE_VOUCHER_DETAILS.GL_CODE UNION ALL SELECT SUM(PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_AMOUNT) AS  TOTAL_EXPENCE_AMOUNT, CONVERT (VARCHAR(15), PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE, 103 ) AS YEAR ,    CHART_OF_ACCOUNTS.GL_DESCRIPTION AS SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_HEADER LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_DETAILS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO = PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO AND PURCHASE_PAYMENT_VOUCHER_DETAILS.CR_AMOUNT  = '0.00' LEFT OUTER JOIN CHART_OF_ACCOUNTS ON CHART_OF_ACCOUNTS.GL_CODE = PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE WHERE PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '11' AND CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE), 103) = CONVERT(VARCHAR(15),GETDATE() -1 , 103) GROUP BY CONVERT (VARCHAR(15),  PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE,103) , CHART_OF_ACCOUNTS.GL_DESCRIPTION ORDER BY YEAR";
                    break;
                case "14":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+7, 101) AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()+7, 101)GROUP BY CONVERT (VARCHAR(15),PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE,103),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+7, 101) AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()+7, 101) GROUP BY CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) , EXPENCE_VOUCHER_DETAILS.GL_CODE UNION ALL SELECT SUM(PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_AMOUNT) AS  TOTAL_EXPENCE_AMOUNT, CONVERT (VARCHAR(15), PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE, 103 ) AS YEAR ,    CHART_OF_ACCOUNTS.GL_DESCRIPTION AS SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_HEADER LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_DETAILS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO = PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO AND PURCHASE_PAYMENT_VOUCHER_DETAILS.CR_AMOUNT  = '0.00' LEFT OUTER JOIN CHART_OF_ACCOUNTS ON CHART_OF_ACCOUNTS.GL_CODE = PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE WHERE PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '11' AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+7, 101) GROUP BY CONVERT (VARCHAR(15),  PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE ,103) , CHART_OF_ACCOUNTS.GL_DESCRIPTION ORDER BY YEAR";
                    break;
                case "15":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()-7, 101) AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()+7, 101)GROUP BY CONVERT (VARCHAR(15),PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE,103),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()-7, 101) AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()+7, 101) GROUP BY CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) , EXPENCE_VOUCHER_DETAILS.GL_CODE UNION ALL SELECT SUM(PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_AMOUNT) AS  TOTAL_EXPENCE_AMOUNT, CONVERT (VARCHAR(15), PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE, 103 ) AS YEAR ,    CHART_OF_ACCOUNTS.GL_DESCRIPTION AS SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_HEADER LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_DETAILS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO = PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO AND PURCHASE_PAYMENT_VOUCHER_DETAILS.CR_AMOUNT  = '0.00' LEFT OUTER JOIN CHART_OF_ACCOUNTS ON CHART_OF_ACCOUNTS.GL_CODE = PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE WHERE PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '11' AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()-7, 101) GROUP BY CONVERT (VARCHAR(15),  PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE ,103) , CHART_OF_ACCOUNTS.GL_DESCRIPTION ORDER BY YEAR";
                    break;
                case "16":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+7, 101) AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()+14, 101)GROUP BY CONVERT (VARCHAR(15),PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE,103),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+7, 101) AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()+14, 101) GROUP BY CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) , EXPENCE_VOUCHER_DETAILS.GL_CODE UNION ALL SELECT SUM(PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_AMOUNT) AS  TOTAL_EXPENCE_AMOUNT, CONVERT (VARCHAR(15), PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE, 103 ) AS YEAR ,    CHART_OF_ACCOUNTS.GL_DESCRIPTION AS SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_HEADER LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_DETAILS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO = PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO AND PURCHASE_PAYMENT_VOUCHER_DETAILS.CR_AMOUNT  = '0.00' LEFT OUTER JOIN CHART_OF_ACCOUNTS ON CHART_OF_ACCOUNTS.GL_CODE = PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE WHERE PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '11' AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+14, 101) GROUP BY CONVERT (VARCHAR(15),  PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE ,103) , CHART_OF_ACCOUNTS.GL_DESCRIPTION ORDER BY YEAR";
                    break;
                case "17":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+7, 101) AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()-14, 101)GROUP BY CONVERT (VARCHAR(15),PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE,103),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()+7, 101) AND CONVERT (VARCHAR(5), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 101) <= CONVERT(VARCHAR(5),GETDATE()-14, 101) GROUP BY CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) , EXPENCE_VOUCHER_DETAILS.GL_CODE UNION ALL SELECT SUM(PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_AMOUNT) AS  TOTAL_EXPENCE_AMOUNT, CONVERT (VARCHAR(15), PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE, 103 ) AS YEAR ,    CHART_OF_ACCOUNTS.GL_DESCRIPTION AS SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_HEADER LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_DETAILS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO = PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO AND PURCHASE_PAYMENT_VOUCHER_DETAILS.CR_AMOUNT  = '0.00' LEFT OUTER JOIN CHART_OF_ACCOUNTS ON CHART_OF_ACCOUNTS.GL_CODE = PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE WHERE PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID = '11' AND CONVERT (VARCHAR(5), ( PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE), 101) >= CONVERT(VARCHAR(5),GETDATE()-14, 101) GROUP BY CONVERT (VARCHAR(15),  PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_DATE ,103) , CHART_OF_ACCOUNTS.GL_DESCRIPTION ORDER BY YEAR";
                    break;
                case "18":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , datename(month,PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND datepart(MONTH,PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE)= '" + System.DateTime.Now.AddMonths(+1).Month + "' datename(month, PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , datename(month,EXPENCE_VOUCHER_DETAILS.POSTED_DATE) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND datepart(MONTH,EXPENCE_VOUCHER_DETAILS.POSTED_DATE)= '" + System.DateTime.Now.AddMonths(-1).Month + "' GROUP BY datename(month,EXPENCE_VOUCHER_DETAILS.POSTED_DATE), EXPENCE_VOUCHER_DETAILS.GL_CODE ORDER BY YEAR";

                    break;
                case "19":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , datename(month,PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND datepart(MONTH,PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE)= '" + System.DateTime.Now.AddMonths(-1).Month + "' datename(month, PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT ,datename(month, EXPENCE_VOUCHER_DETAILS.POSTED_DATE) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND datepart(MONTH,EXPENCE_VOUCHER_DETAILS.POSTED_DATE)= '" + System.DateTime.Now.AddMonths(+1).Month + "' GROUP BY datename(month,EXPENCE_VOUCHER_DETAILS.POSTED_DATE) , EXPENCE_VOUCHER_DETAILS.GL_CODE ORDER BY YEAR";
                    break;
                case "20":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , datename(month, PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND datepart(MONTH,PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE)= '" + System.DateTime.Now.Month + "' GROUP BY CONVERT datename(month, PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , datename(month, EXPENCE_VOUCHER_DETAILS.POSTED_DATE) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND datepart(MONTH,EXPENCE_VOUCHER_DETAILS.POSTED_DATE)= '" + System.DateTime.Now.Month + "'  datename(month,EXPENCE_VOUCHER_DETAILS.POSTED_DATE), EXPENCE_VOUCHER_DETAILS.GL_CODE ORDER BY YEAR";
                    break;
                case "21":
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL AND CONVERT (VARCHAR(15), ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE), 103) = CONVERT(VARCHAR(15),GETDATE()+1, 103) GROUP BY CONVERT (VARCHAR(15),PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE,103),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' AND CONVERT (VARCHAR(15), ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE), 103) = CONVERT(VARCHAR(15),GETDATE()+1, 103) GROUP BY CONVERT (VARCHAR(15), EXPENCE_VOUCHER_DETAILS.POSTED_DATE, 103) , EXPENCE_VOUCHER_DETAILS.GL_CODE ORDER BY YEAR";
                    break;
                default:
                    query = "SELECT SUM (PURCHASE_PAYMENT_VOUCHER_DETAILS.DR_AMOUNT) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), YEAR ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE)) AS YEAR ,SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME FROM PURCHASE_PAYMENT_VOUCHER_DETAILS LEFT OUTER JOIN PURCHASE_PAYMENT_VOUCHER_HEADER ON PURCHASE_PAYMENT_VOUCHER_HEADER.SEQ_NO=PURCHASE_PAYMENT_VOUCHER_DETAILS.SEQ_NO LEFT OUTER JOIN ACCOUNTS_VOUCHER_TYPE_MASTER ON ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE_ID =PURCHASE_PAYMENT_VOUCHER_HEADER.VOUCHER_TYPE_ID LEFT OUTER JOIN CHART_OF_ACCOUNTS ON PURCHASE_PAYMENT_VOUCHER_DETAILS.GL_CODE=CHART_OF_ACCOUNTS.GL_CODE LEFT OUTER JOIN SUPPLIER_MASTER ON CHART_OF_ACCOUNTS.ACCOUNT_ID  = SUPPLIER_MASTER.SUPPLIER_ID LEFT OUTER JOIN SUPPLIER_TYPE_MASTER ON SUPPLIER_MASTER.SUPPLIER_TYPE_ID = SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID WHERE SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME  IS NOT NULL GROUP BY CONVERT (VARCHAR(15), YEAR ( PURCHASE_PAYMENT_VOUCHER_DETAILS.POSTED_DATE)),ACCOUNTS_VOUCHER_TYPE_MASTER.VOUCHER_TYPE  , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_ID , SUPPLIER_TYPE_MASTER.SUPPLIER_TYPE_NAME UNION ALL SELECT  SUM (EXPENCE_VOUCHER_DETAILS.CR_AMOUNT ) AS TOTAL_EXPENCE_AMOUNT , CONVERT (VARCHAR(15), YEAR ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE)) AS YEAR , EXPENCE_VOUCHER_DETAILS.GL_CODE AS SUPPLIER_TYPE_NAME  FROM EXPENCE_VOUCHER_DETAILS WHERE EXPENCE_VOUCHER_DETAILS.CR_AMOUNT != '0.00' GROUP BY YEAR ( EXPENCE_VOUCHER_DETAILS.POSTED_DATE) , EXPENCE_VOUCHER_DETAILS.GL_CODE ORDER BY YEAR";
                    break;
            }
            //END QUERY
            //END QUERY
            DataTable _dttemp = new DataTable();
            DataTable dt = new DataTable();
            try
            {
                dt = objdeshboardentity.ExecuteQuery(query.ToString().Trim()).Tables[0];

                _dttemp.Columns.Add("CUSTOMER_TYPE", typeof(string));
                _dttemp.Columns.Add("TOTAL", typeof(int));
                _dttemp.Rows.Add(_dttemp.NewRow());
                _dttemp.Rows.Add(_dttemp.NewRow());
                _dttemp.Rows[0]["TOTAL"] = 0;
                _dttemp.Rows[1]["TOTAL"] = 0;
                // Add series into the chart's series collection
                foreach (DataRow dr in _dttemp.Rows)
                {
                    try
                    {
                        if (dr["TOTAL"].ToString() == "1")
                        {
                            _dttemp.Rows[0]["CUSTOMER_TYPE"] = "New";
                            _dttemp.Rows[0]["TOTAL"] = int.Parse(_dttemp.Rows[0]["TOTAL"].ToString()) + int.Parse(dr["TOTAL"].ToString());
                        }
                        else
                        {
                            _dttemp.Rows[1]["CUSTOMER_TYPE"] = "Old";
                            _dttemp.Rows[1]["TOTAL"] = int.Parse(_dttemp.Rows[0]["TOTAL"].ToString()) + int.Parse(dr["TOTAL"].ToString());

                        }
                    }
                    catch (Exception ex)
                    {

                    }
                }
            }
            catch (Exception ex) { }
            try
            {
                DataTable dt1 = objdeshboardentity.ExecuteQuery(query.ToString().Trim()).Tables[0];
                //SqlConnection con = new SqlConnection(str);
                //con.Open();

                //SqlCommand cmd = new SqlCommand("GEDJET_EXPENCE_COMPANRASION", con);
                //cmd.CommandType = CommandType.StoredProcedure;
                //SqlDataReader rdr = cmd.ExecuteReader();
                //DataTable dt1 = new DataTable();
                //dt.Load(rdr);

                Chart1.Series.Add(series);
                series.XValueMember = "SUPPLIER_TYPE_NAME";
                series.YValueMembers = "TOTAL_EXPENCE_AMOUNT";
                series.IsValueShownAsLabel = true;
                //    Chart1.ChartAreas[0].AxisY.Maximum = int.Parse(dt.Rows[0]["TOTAL_RECEIPT_AMOUNT"].ToString());


                Chart1.DataSource = dt1;
                Chart1.DataBind();
            }
            catch
            {
            }
        }

        #region Web Form Designer generated code
        override protected void OnInit(EventArgs e)
        {
            //
            // CODEGEN: This call is required by the ASP.NET Web Form Designer.
            //
            InitializeComponent();
            base.OnInit(e);
        }

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {

        }
        #endregion
        }
    }
