#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THAILAND_CRM")]
	public partial class AccountsGroupDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AccountsGroupDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["THAILAND_CRMConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsGroupDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsGroupDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsGroupDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountsGroupDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_ACCOUNT_GROUP_MASTER> VIEW_ACCOUNT_GROUP_MASTERs
		{
			get
			{
				return this.GetTable<VIEW_ACCOUNT_GROUP_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_ACCOUNT_GROUP_MASTER")]
	public partial class VIEW_ACCOUNT_GROUP_MASTER
	{
		
		private int _ACCOUNT_GROUP_ID;
		
		private string _GROUP_CODE;
		
		private string _GROUP_NAME;
		
		private string _GROUP_TYPE;
		
		private string _GROUP_DISPLAY_NAME;
		
		private System.Nullable<int> _GROUP_ORDER;
		
		private string _GROUP_CODE_UNDER;
		
		private string _COMPANY_NAME;
		
		public VIEW_ACCOUNT_GROUP_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_GROUP_ID", DbType="Int NOT NULL")]
		public int ACCOUNT_GROUP_ID
		{
			get
			{
				return this._ACCOUNT_GROUP_ID;
			}
			set
			{
				if ((this._ACCOUNT_GROUP_ID != value))
				{
					this._ACCOUNT_GROUP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_CODE", DbType="VarChar(100)")]
		public string GROUP_CODE
		{
			get
			{
				return this._GROUP_CODE;
			}
			set
			{
				if ((this._GROUP_CODE != value))
				{
					this._GROUP_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_NAME", DbType="VarChar(100)")]
		public string GROUP_NAME
		{
			get
			{
				return this._GROUP_NAME;
			}
			set
			{
				if ((this._GROUP_NAME != value))
				{
					this._GROUP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_TYPE", DbType="VarChar(MAX)")]
		public string GROUP_TYPE
		{
			get
			{
				return this._GROUP_TYPE;
			}
			set
			{
				if ((this._GROUP_TYPE != value))
				{
					this._GROUP_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_DISPLAY_NAME", DbType="VarChar(100)")]
		public string GROUP_DISPLAY_NAME
		{
			get
			{
				return this._GROUP_DISPLAY_NAME;
			}
			set
			{
				if ((this._GROUP_DISPLAY_NAME != value))
				{
					this._GROUP_DISPLAY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Int")]
		public System.Nullable<int> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_CODE_UNDER", DbType="VarChar(100)")]
		public string GROUP_CODE_UNDER
		{
			get
			{
				return this._GROUP_CODE_UNDER;
			}
			set
			{
				if ((this._GROUP_CODE_UNDER != value))
				{
					this._GROUP_CODE_UNDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(100)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this._COMPANY_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
