#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FULL_CRM_ASHISH")]
	public partial class BookingFormStep1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BookingFormStep1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FULL_CRM_ASHISHConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BookingFormStep1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookingFormStep1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookingFormStep1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookingFormStep1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_FOR_CUSTOMER_DETAIL_NEW> VIEW_FOR_CUSTOMER_DETAIL_NEWs
		{
			get
			{
				return this.GetTable<VIEW_FOR_CUSTOMER_DETAIL_NEW>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_FOR_CUSTOMER_RELATION_NEW> VIEW_FOR_CUSTOMER_RELATION_NEWs
		{
			get
			{
				return this.GetTable<VIEW_FOR_CUSTOMER_RELATION_NEW>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_FOR_CUSTOMER_VISA_DETAIL_NEW> VIEW_FOR_CUSTOMER_VISA_DETAIL_NEWs
		{
			get
			{
				return this.GetTable<VIEW_FOR_CUSTOMER_VISA_DETAIL_NEW>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_FOR_CUSTOMER_DETAIL_NEW")]
	public partial class VIEW_FOR_CUSTOMER_DETAIL_NEW
	{
		
		private System.Nullable<long> _INQUIRY_ID;
		
		private System.Nullable<int> _CUST_ID;
		
		private string _CUST_UNQ_ID;
		
		private string _CUST_TYPE;
		
		private string _REL_TITLE;
		
		private string _REL_NAME;
		
		private string _REL_SURNAME;
		
		private string _REL_EMAIL;
		
		private string _REL_MOBILE;
		
		private string _REL_PHONE;
		
		private string _REL_ADDRESS_LINE1;
		
		private string _REL_ADDRESS_LINE2;
		
		private string _REL_CITY_NAME;
		
		private string _REL_STATE_NAME;
		
		private string _REL_COUNTRY_NAME;
		
		private string _REL_PINCODE;
		
		private string _EMM_NAME;
		
		private string _EMM_ADDRESS_LINE1;
		
		private string _EMM_ADDRESS_LINE2;
		
		private string _EMM_CITY_NAME;
		
		private string _EMM_STATE_NAME;
		
		private string _EMM_COUNTRY_NAME;
		
		private string _EMM_PINCODE;
		
		private System.Nullable<int> _REL_SRNO;
		
		private System.Nullable<int> _EMM_SRNO;
		
		private string _EMM_MOBILE;
		
		private string _EMM_PHONE;
		
		public VIEW_FOR_CUSTOMER_DETAIL_NEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INQUIRY_ID", DbType="BigInt")]
		public System.Nullable<long> INQUIRY_ID
		{
			get
			{
				return this._INQUIRY_ID;
			}
			set
			{
				if ((this._INQUIRY_ID != value))
				{
					this._INQUIRY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ID", DbType="Int")]
		public System.Nullable<int> CUST_ID
		{
			get
			{
				return this._CUST_ID;
			}
			set
			{
				if ((this._CUST_ID != value))
				{
					this._CUST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_UNQ_ID", DbType="NVarChar(50)")]
		public string CUST_UNQ_ID
		{
			get
			{
				return this._CUST_UNQ_ID;
			}
			set
			{
				if ((this._CUST_UNQ_ID != value))
				{
					this._CUST_UNQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_TYPE", DbType="VarChar(50)")]
		public string CUST_TYPE
		{
			get
			{
				return this._CUST_TYPE;
			}
			set
			{
				if ((this._CUST_TYPE != value))
				{
					this._CUST_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_TITLE", DbType="VarChar(10)")]
		public string REL_TITLE
		{
			get
			{
				return this._REL_TITLE;
			}
			set
			{
				if ((this._REL_TITLE != value))
				{
					this._REL_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_NAME", DbType="VarChar(255)")]
		public string REL_NAME
		{
			get
			{
				return this._REL_NAME;
			}
			set
			{
				if ((this._REL_NAME != value))
				{
					this._REL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_SURNAME", DbType="VarChar(50)")]
		public string REL_SURNAME
		{
			get
			{
				return this._REL_SURNAME;
			}
			set
			{
				if ((this._REL_SURNAME != value))
				{
					this._REL_SURNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_EMAIL", DbType="VarChar(100)")]
		public string REL_EMAIL
		{
			get
			{
				return this._REL_EMAIL;
			}
			set
			{
				if ((this._REL_EMAIL != value))
				{
					this._REL_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_MOBILE", DbType="VarChar(15)")]
		public string REL_MOBILE
		{
			get
			{
				return this._REL_MOBILE;
			}
			set
			{
				if ((this._REL_MOBILE != value))
				{
					this._REL_MOBILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PHONE", DbType="VarChar(100)")]
		public string REL_PHONE
		{
			get
			{
				return this._REL_PHONE;
			}
			set
			{
				if ((this._REL_PHONE != value))
				{
					this._REL_PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_ADDRESS_LINE1", DbType="NVarChar(400)")]
		public string REL_ADDRESS_LINE1
		{
			get
			{
				return this._REL_ADDRESS_LINE1;
			}
			set
			{
				if ((this._REL_ADDRESS_LINE1 != value))
				{
					this._REL_ADDRESS_LINE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_ADDRESS_LINE2", DbType="NVarChar(400)")]
		public string REL_ADDRESS_LINE2
		{
			get
			{
				return this._REL_ADDRESS_LINE2;
			}
			set
			{
				if ((this._REL_ADDRESS_LINE2 != value))
				{
					this._REL_ADDRESS_LINE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_CITY_NAME", DbType="VarChar(50)")]
		public string REL_CITY_NAME
		{
			get
			{
				return this._REL_CITY_NAME;
			}
			set
			{
				if ((this._REL_CITY_NAME != value))
				{
					this._REL_CITY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_STATE_NAME", DbType="VarChar(50)")]
		public string REL_STATE_NAME
		{
			get
			{
				return this._REL_STATE_NAME;
			}
			set
			{
				if ((this._REL_STATE_NAME != value))
				{
					this._REL_STATE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_COUNTRY_NAME", DbType="VarChar(50)")]
		public string REL_COUNTRY_NAME
		{
			get
			{
				return this._REL_COUNTRY_NAME;
			}
			set
			{
				if ((this._REL_COUNTRY_NAME != value))
				{
					this._REL_COUNTRY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PINCODE", DbType="VarChar(20)")]
		public string REL_PINCODE
		{
			get
			{
				return this._REL_PINCODE;
			}
			set
			{
				if ((this._REL_PINCODE != value))
				{
					this._REL_PINCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_NAME", DbType="VarChar(100)")]
		public string EMM_NAME
		{
			get
			{
				return this._EMM_NAME;
			}
			set
			{
				if ((this._EMM_NAME != value))
				{
					this._EMM_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_ADDRESS_LINE1", DbType="NVarChar(400)")]
		public string EMM_ADDRESS_LINE1
		{
			get
			{
				return this._EMM_ADDRESS_LINE1;
			}
			set
			{
				if ((this._EMM_ADDRESS_LINE1 != value))
				{
					this._EMM_ADDRESS_LINE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_ADDRESS_LINE2", DbType="NVarChar(400)")]
		public string EMM_ADDRESS_LINE2
		{
			get
			{
				return this._EMM_ADDRESS_LINE2;
			}
			set
			{
				if ((this._EMM_ADDRESS_LINE2 != value))
				{
					this._EMM_ADDRESS_LINE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_CITY_NAME", DbType="VarChar(50)")]
		public string EMM_CITY_NAME
		{
			get
			{
				return this._EMM_CITY_NAME;
			}
			set
			{
				if ((this._EMM_CITY_NAME != value))
				{
					this._EMM_CITY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_STATE_NAME", DbType="VarChar(50)")]
		public string EMM_STATE_NAME
		{
			get
			{
				return this._EMM_STATE_NAME;
			}
			set
			{
				if ((this._EMM_STATE_NAME != value))
				{
					this._EMM_STATE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_COUNTRY_NAME", DbType="VarChar(50)")]
		public string EMM_COUNTRY_NAME
		{
			get
			{
				return this._EMM_COUNTRY_NAME;
			}
			set
			{
				if ((this._EMM_COUNTRY_NAME != value))
				{
					this._EMM_COUNTRY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_PINCODE", DbType="VarChar(20)")]
		public string EMM_PINCODE
		{
			get
			{
				return this._EMM_PINCODE;
			}
			set
			{
				if ((this._EMM_PINCODE != value))
				{
					this._EMM_PINCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_SRNO", DbType="Int")]
		public System.Nullable<int> REL_SRNO
		{
			get
			{
				return this._REL_SRNO;
			}
			set
			{
				if ((this._REL_SRNO != value))
				{
					this._REL_SRNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_SRNO", DbType="Int")]
		public System.Nullable<int> EMM_SRNO
		{
			get
			{
				return this._EMM_SRNO;
			}
			set
			{
				if ((this._EMM_SRNO != value))
				{
					this._EMM_SRNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_MOBILE", DbType="VarChar(100)")]
		public string EMM_MOBILE
		{
			get
			{
				return this._EMM_MOBILE;
			}
			set
			{
				if ((this._EMM_MOBILE != value))
				{
					this._EMM_MOBILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMM_PHONE", DbType="VarChar(100)")]
		public string EMM_PHONE
		{
			get
			{
				return this._EMM_PHONE;
			}
			set
			{
				if ((this._EMM_PHONE != value))
				{
					this._EMM_PHONE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_FOR_CUSTOMER_RELATION_NEW")]
	public partial class VIEW_FOR_CUSTOMER_RELATION_NEW
	{
		
		private int _CUST_REL_SRNO;
		
		private string _CUST_UNQ_ID;
		
		private System.Nullable<int> _CUST_ID;
		
		private string _REL_TITLE;
		
		private string _REL_SURNAME;
		
		private string _REL_NAME;
		
		private string _RELATION;
		
		private int _CUST_REL_ID;
		
		private string _REL_BIRTH_DATE;
		
		private string _REL_EMAIL;
		
		private string _REL_MOBILE;
		
		private string _REL_PHONE;
		
		private string _REL_PASSPORT_NO;
		
		private string _REL_PASSPORT_ISSUE_DATE;
		
		private string _REL_PASSPORT_ISSUE_PLACE;
		
		private string _REL_PASSPORT_EXPIRY_DATE;
		
		private string _REL_PASSPORT_PRINTED_NAME;
		
		private string _REL_PASSPORT_ISSUE_COUNTRY;
		
		private string _MEAL_NAME;
		
		private string _NATIONALITY;
		
		public VIEW_FOR_CUSTOMER_RELATION_NEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REL_SRNO", DbType="Int NOT NULL")]
		public int CUST_REL_SRNO
		{
			get
			{
				return this._CUST_REL_SRNO;
			}
			set
			{
				if ((this._CUST_REL_SRNO != value))
				{
					this._CUST_REL_SRNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_UNQ_ID", DbType="NVarChar(50)")]
		public string CUST_UNQ_ID
		{
			get
			{
				return this._CUST_UNQ_ID;
			}
			set
			{
				if ((this._CUST_UNQ_ID != value))
				{
					this._CUST_UNQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ID", DbType="Int")]
		public System.Nullable<int> CUST_ID
		{
			get
			{
				return this._CUST_ID;
			}
			set
			{
				if ((this._CUST_ID != value))
				{
					this._CUST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_TITLE", DbType="VarChar(10)")]
		public string REL_TITLE
		{
			get
			{
				return this._REL_TITLE;
			}
			set
			{
				if ((this._REL_TITLE != value))
				{
					this._REL_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_SURNAME", DbType="VarChar(50)")]
		public string REL_SURNAME
		{
			get
			{
				return this._REL_SURNAME;
			}
			set
			{
				if ((this._REL_SURNAME != value))
				{
					this._REL_SURNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_NAME", DbType="VarChar(255)")]
		public string REL_NAME
		{
			get
			{
				return this._REL_NAME;
			}
			set
			{
				if ((this._REL_NAME != value))
				{
					this._REL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELATION", DbType="VarChar(25)")]
		public string RELATION
		{
			get
			{
				return this._RELATION;
			}
			set
			{
				if ((this._RELATION != value))
				{
					this._RELATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REL_ID", DbType="Int NOT NULL")]
		public int CUST_REL_ID
		{
			get
			{
				return this._CUST_REL_ID;
			}
			set
			{
				if ((this._CUST_REL_ID != value))
				{
					this._CUST_REL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_BIRTH_DATE", DbType="VarChar(10)")]
		public string REL_BIRTH_DATE
		{
			get
			{
				return this._REL_BIRTH_DATE;
			}
			set
			{
				if ((this._REL_BIRTH_DATE != value))
				{
					this._REL_BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_EMAIL", DbType="VarChar(100)")]
		public string REL_EMAIL
		{
			get
			{
				return this._REL_EMAIL;
			}
			set
			{
				if ((this._REL_EMAIL != value))
				{
					this._REL_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_MOBILE", DbType="VarChar(15)")]
		public string REL_MOBILE
		{
			get
			{
				return this._REL_MOBILE;
			}
			set
			{
				if ((this._REL_MOBILE != value))
				{
					this._REL_MOBILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PHONE", DbType="VarChar(100)")]
		public string REL_PHONE
		{
			get
			{
				return this._REL_PHONE;
			}
			set
			{
				if ((this._REL_PHONE != value))
				{
					this._REL_PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PASSPORT_NO", DbType="VarChar(25)")]
		public string REL_PASSPORT_NO
		{
			get
			{
				return this._REL_PASSPORT_NO;
			}
			set
			{
				if ((this._REL_PASSPORT_NO != value))
				{
					this._REL_PASSPORT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PASSPORT_ISSUE_DATE", DbType="VarChar(10)")]
		public string REL_PASSPORT_ISSUE_DATE
		{
			get
			{
				return this._REL_PASSPORT_ISSUE_DATE;
			}
			set
			{
				if ((this._REL_PASSPORT_ISSUE_DATE != value))
				{
					this._REL_PASSPORT_ISSUE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PASSPORT_ISSUE_PLACE", DbType="VarChar(20)")]
		public string REL_PASSPORT_ISSUE_PLACE
		{
			get
			{
				return this._REL_PASSPORT_ISSUE_PLACE;
			}
			set
			{
				if ((this._REL_PASSPORT_ISSUE_PLACE != value))
				{
					this._REL_PASSPORT_ISSUE_PLACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PASSPORT_EXPIRY_DATE", DbType="VarChar(10)")]
		public string REL_PASSPORT_EXPIRY_DATE
		{
			get
			{
				return this._REL_PASSPORT_EXPIRY_DATE;
			}
			set
			{
				if ((this._REL_PASSPORT_EXPIRY_DATE != value))
				{
					this._REL_PASSPORT_EXPIRY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PASSPORT_PRINTED_NAME", DbType="VarChar(100)")]
		public string REL_PASSPORT_PRINTED_NAME
		{
			get
			{
				return this._REL_PASSPORT_PRINTED_NAME;
			}
			set
			{
				if ((this._REL_PASSPORT_PRINTED_NAME != value))
				{
					this._REL_PASSPORT_PRINTED_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_PASSPORT_ISSUE_COUNTRY", DbType="VarChar(20)")]
		public string REL_PASSPORT_ISSUE_COUNTRY
		{
			get
			{
				return this._REL_PASSPORT_ISSUE_COUNTRY;
			}
			set
			{
				if ((this._REL_PASSPORT_ISSUE_COUNTRY != value))
				{
					this._REL_PASSPORT_ISSUE_COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEAL_NAME", DbType="VarChar(255)")]
		public string MEAL_NAME
		{
			get
			{
				return this._MEAL_NAME;
			}
			set
			{
				if ((this._MEAL_NAME != value))
				{
					this._MEAL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATIONALITY", DbType="VarChar(255)")]
		public string NATIONALITY
		{
			get
			{
				return this._NATIONALITY;
			}
			set
			{
				if ((this._NATIONALITY != value))
				{
					this._NATIONALITY = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_FOR_CUSTOMER_VISA_DETAIL_NEW")]
	public partial class VIEW_FOR_CUSTOMER_VISA_DETAIL_NEW
	{
		
		private System.Nullable<int> _CUST_ID;
		
		private System.Nullable<int> _COUNTRY_ID;
		
		private string _VISA_EXPIRY_DATE;
		
		private string _COUNTRY_NAME;
		
		private System.Nullable<int> _CUST_REL_SRNO;
		
		private System.Nullable<int> _CUST_REL_ID;
		
		public VIEW_FOR_CUSTOMER_VISA_DETAIL_NEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ID", DbType="Int")]
		public System.Nullable<int> CUST_ID
		{
			get
			{
				return this._CUST_ID;
			}
			set
			{
				if ((this._CUST_ID != value))
				{
					this._CUST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_ID", DbType="Int")]
		public System.Nullable<int> COUNTRY_ID
		{
			get
			{
				return this._COUNTRY_ID;
			}
			set
			{
				if ((this._COUNTRY_ID != value))
				{
					this._COUNTRY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISA_EXPIRY_DATE", DbType="VarChar(10)")]
		public string VISA_EXPIRY_DATE
		{
			get
			{
				return this._VISA_EXPIRY_DATE;
			}
			set
			{
				if ((this._VISA_EXPIRY_DATE != value))
				{
					this._VISA_EXPIRY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_NAME", DbType="VarChar(50)")]
		public string COUNTRY_NAME
		{
			get
			{
				return this._COUNTRY_NAME;
			}
			set
			{
				if ((this._COUNTRY_NAME != value))
				{
					this._COUNTRY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REL_SRNO", DbType="Int")]
		public System.Nullable<int> CUST_REL_SRNO
		{
			get
			{
				return this._CUST_REL_SRNO;
			}
			set
			{
				if ((this._CUST_REL_SRNO != value))
				{
					this._CUST_REL_SRNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REL_ID", DbType="Int")]
		public System.Nullable<int> CUST_REL_ID
		{
			get
			{
				return this._CUST_REL_ID;
			}
			set
			{
				if ((this._CUST_REL_ID != value))
				{
					this._CUST_REL_ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
