<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="BookingCurrencyMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=122.169.106.88;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_BOOKING_CURRENCY_MASTER" Member="VIEW_BOOKING_CURRENCY_MASTERs">
    <Type Name="VIEW_BOOKING_CURRENCY_MASTER">
      <Column Name="CURRENCY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CURRENCY_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CURRENCY_SYMBOL" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
    </Type>
  </Table>
</Database>