#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FULL_CRM_ASHISH")]
	public partial class BusinessCompanyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BusinessCompanyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessCompanyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessCompanyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessCompanyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BusinessCompanyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_BUSINESS_COMPANY> VIEW_BUSINESS_COMPANies
		{
			get
			{
				return this.GetTable<VIEW_BUSINESS_COMPANY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_BUSINESS_COMPANY")]
	public partial class VIEW_BUSINESS_COMPANY
	{
		
		private int _COMPANY_ID;
		
		private System.Nullable<char> _IS_COMPANY_FRANCHISE;
		
		private string _COMPANY_NAME;
		
		private string _ADDRESS_LINE1;
		
		private string _ADDRESS_LINE2;
		
		private string _PINCODE;
		
		private string _MOBILE;
		
		private string _PHONE;
		
		private string _FAX;
		
		private string _EMAIL_ID;
		
		private System.Nullable<int> _CREATED_BY;
		
		private System.Nullable<System.DateTime> _CREATED_ON;
		
		private System.Nullable<int> _MODIFIED_BY;
		
		private System.Nullable<System.DateTime> _MODIFIED_ON;
		
		private string _REGION_SHORT_NAME;
		
		private string _CITY_NAME;
		
		private string _COUNTRY_NAME;
		
		private string _STATE_NAME;
		
		private string _PARENT_NAME;
		
		public VIEW_BUSINESS_COMPANY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_ID", DbType="Int NOT NULL")]
		public int COMPANY_ID
		{
			get
			{
				return this._COMPANY_ID;
			}
			set
			{
				if ((this._COMPANY_ID != value))
				{
					this._COMPANY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_COMPANY_FRANCHISE", DbType="Char(1)")]
		public System.Nullable<char> IS_COMPANY_FRANCHISE
		{
			get
			{
				return this._IS_COMPANY_FRANCHISE;
			}
			set
			{
				if ((this._IS_COMPANY_FRANCHISE != value))
				{
					this._IS_COMPANY_FRANCHISE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(100)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this._COMPANY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_LINE1", DbType="VarChar(100)")]
		public string ADDRESS_LINE1
		{
			get
			{
				return this._ADDRESS_LINE1;
			}
			set
			{
				if ((this._ADDRESS_LINE1 != value))
				{
					this._ADDRESS_LINE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_LINE2", DbType="VarChar(100)")]
		public string ADDRESS_LINE2
		{
			get
			{
				return this._ADDRESS_LINE2;
			}
			set
			{
				if ((this._ADDRESS_LINE2 != value))
				{
					this._ADDRESS_LINE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PINCODE", DbType="VarChar(8)")]
		public string PINCODE
		{
			get
			{
				return this._PINCODE;
			}
			set
			{
				if ((this._PINCODE != value))
				{
					this._PINCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE", DbType="VarChar(12)")]
		public string MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this._MOBILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(50)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(25)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this._FAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ID", DbType="VarChar(50)")]
		public string EMAIL_ID
		{
			get
			{
				return this._EMAIL_ID;
			}
			set
			{
				if ((this._EMAIL_ID != value))
				{
					this._EMAIL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="Int")]
		public System.Nullable<int> CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this._CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_ON", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_ON
		{
			get
			{
				return this._CREATED_ON;
			}
			set
			{
				if ((this._CREATED_ON != value))
				{
					this._CREATED_ON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_BY", DbType="Int")]
		public System.Nullable<int> MODIFIED_BY
		{
			get
			{
				return this._MODIFIED_BY;
			}
			set
			{
				if ((this._MODIFIED_BY != value))
				{
					this._MODIFIED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_ON", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFIED_ON
		{
			get
			{
				return this._MODIFIED_ON;
			}
			set
			{
				if ((this._MODIFIED_ON != value))
				{
					this._MODIFIED_ON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION_SHORT_NAME", DbType="NVarChar(25)")]
		public string REGION_SHORT_NAME
		{
			get
			{
				return this._REGION_SHORT_NAME;
			}
			set
			{
				if ((this._REGION_SHORT_NAME != value))
				{
					this._REGION_SHORT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_NAME", DbType="VarChar(50)")]
		public string CITY_NAME
		{
			get
			{
				return this._CITY_NAME;
			}
			set
			{
				if ((this._CITY_NAME != value))
				{
					this._CITY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_NAME", DbType="VarChar(50)")]
		public string COUNTRY_NAME
		{
			get
			{
				return this._COUNTRY_NAME;
			}
			set
			{
				if ((this._COUNTRY_NAME != value))
				{
					this._COUNTRY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_NAME", DbType="VarChar(50)")]
		public string STATE_NAME
		{
			get
			{
				return this._STATE_NAME;
			}
			set
			{
				if ((this._STATE_NAME != value))
				{
					this._STATE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_NAME", DbType="VarChar(100)")]
		public string PARENT_NAME
		{
			get
			{
				return this._PARENT_NAME;
			}
			set
			{
				if ((this._PARENT_NAME != value))
				{
					this._PARENT_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
