<?xml version="1.0" encoding="utf-8"?><Database Name="FULL_CRM_ASHISH" Class="Campaign2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.12;Initial Catalog=FULL_CRM_ASHISH;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_COMPAIGN_MARKETING_MAPPING" Member="VIEW_COMPAIGN_MARKETING_MAPPINGs">
    <Type Name="VIEW_COMPAIGN_MARKETING_MAPPING">
      <Column Name="CAMPAIGN_NAME" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TOUR_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CAMPAIGN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOUR_SHORT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TOUR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAMP_MAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_COMAPAIGN_TARGETLIST_DETAILS" Member="VIEW_COMAPAIGN_TARGETLIST_DETAILs">
    <Type Name="VIEW_COMAPAIGN_TARGETLIST_DETAIL">
      <Column Name="TARGET_DETAILS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TARGETLIST_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CAMPAIGN_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CUST_TYPE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TARGETLIST_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAMPAIGN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>