#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FULL_CRM_ASHISH")]
	public partial class CompanyMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CompanyMasterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CompanyMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_CUST_COMPANY_MASTER> VIEW_CUST_COMPANY_MASTERs
		{
			get
			{
				return this.GetTable<VIEW_CUST_COMPANY_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_CUST_COMPANY_MASTER")]
	public partial class VIEW_CUST_COMPANY_MASTER
	{
		
		private int _CUST_COMPANY_ID;
		
		private string _CUST_COMPANY_NAME;
		
		public VIEW_CUST_COMPANY_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_COMPANY_ID", DbType="Int NOT NULL")]
		public int CUST_COMPANY_ID
		{
			get
			{
				return this._CUST_COMPANY_ID;
			}
			set
			{
				if ((this._CUST_COMPANY_ID != value))
				{
					this._CUST_COMPANY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_COMPANY_NAME", DbType="VarChar(255)")]
		public string CUST_COMPANY_NAME
		{
			get
			{
				return this._CUST_COMPANY_NAME;
			}
			set
			{
				if ((this._CUST_COMPANY_NAME != value))
				{
					this._CUST_COMPANY_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
