<?xml version="1.0" encoding="utf-8"?><Database Name="FULL_CRM_ASHISH" Class="CompititorAgentNewDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.6;Initial Catalog=FULL_CRM_ASHISH;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_COMPITITOR_AGENT" Member="VIEW_COMPITITOR_AGENTs">
    <Type Name="VIEW_COMPITITOR_AGENT">
      <Column Name="AGENT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AGENT_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AGENT_ADDRESS" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PHONE_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZIP_POSTAL_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="STRENGTH" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COUNTRY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>