<?xml version="1.0" encoding="utf-8"?><Database Name="FULL_CRM_ASHISH" Class="CompanyMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVER;Initial Catalog=FULL_CRM_ASHISH;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_CUST_COMPANY_MASTER" Member="VIEW_CUST_COMPANY_MASTERs">
    <Type Name="VIEW_CUST_COMPANY_MASTER">
      <Column Name="CUST_COMPANY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUST_COMPANY_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>