<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="CruisePriceSupplierDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.13;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_SUPPLIER_CRUISE_CABINE_INVENTORY" Member="VIEW_SUPPLIER_CRUISE_CABINE_INVENTORies">
    <Type Name="VIEW_SUPPLIER_CRUISE_CABINE_INVENTORY">
      <Column Name="SUPPLIER_CRUISE_CABIN_INVENTORY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUPPLIER_CRUISE_PRICE_LIST_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NO_OF_CABINS_PURCHASED" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NO_OF_CABINS_AVAILABLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_SUPPLIER_CRUISE_PRICE_LIST" Member="VIEW_SUPPLIER_CRUISE_PRICE_LISTs">
    <Type Name="VIEW_SUPPLIER_CRUISE_PRICE_LIST">
      <Column Name="SUPPLIER_CRUISE_PRICE_LIST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EFFECTIVE_FROM_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SUPPLIER_SR_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EFFECTIVE_TO_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CATEGORY_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DECK_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CRUISE_VIEW" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="GIT_RATE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="FIT_RATE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="FIT_DISCOUNT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="GIT_DISCOUNT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="MARGIN_AMOUNT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="MARGIN_AMOUNT_IN_PERCENTAGE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="AUTO_BOOK_ON_LOW_INVENTORY" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="UPLOAD_RATE_DOCUMENT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CURRENCY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYMENT_TERMS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUSTOMER_NAME" Type="System.String" DbType="VarChar(306)" CanBeNull="true" />
      <Column Name="SUPPLIER_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CRUISE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GIT_MARGIN_AMOUNT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="GIT_MARGIN_AMOUNT_IN_PERCENTAGE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="EXTRA_CNB_COST" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="EXTRA_CWB_COST" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="EXTRA_ADULT_RATE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="DOUBLE_ROOM_RATE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="SINGLE_ROOM_RATE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="TO_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FROM_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>