<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="CustomerMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WIN-9XIKFMJP2A9;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_CUST_CUSTOMER_MESSAGE" Member="VIEW_CUST_CUSTOMER_MESSAGEs">
    <Type Name="VIEW_CUST_CUSTOMER_MESSAGE">
      <Column Name="CUST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUSTOMER_NAME" Type="System.String" DbType="VarChar(306)" CanBeNull="true" />
      <Column Name="CUST_REL_MOBILE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_CUST_CUSTOMER_DOCUMENT" Member="VIEW_CUST_CUSTOMER_DOCUMENTs">
    <Type Name="VIEW_CUST_CUSTOMER_DOCUMENT">
      <Column Name="CUST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUST_UNQ_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CUSTOMER_NAME" Type="System.String" DbType="VarChar(306)" CanBeNull="true" />
      <Column Name="SR_NO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUST_REL_SRNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOC_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOC_DESCRIPTION" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DOC_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DOC_FILE_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DOC_FILE_PATH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DOC_FILE_SIZE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_CUST_CUSTOMER_RELATION" Member="VIEW_CUST_CUSTOMER_RELATIONs">
    <Type Name="VIEW_CUST_CUSTOMER_RELATION">
      <Column Name="CUST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUST_UNQ_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CUST_REL_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUST_REL_SRNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TITLE_DESC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUST_REL_SURNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_REL_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CUST_REL_GENDER" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="CUST_REL_MOBILE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CUST_REL_EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CUST_REL_PHONE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RELATION_DESC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PROFESSION_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_REL_ANNUAL_INCOME" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_NO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_PRINTED_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_ISSUE_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_EXPIRY_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_ISSUE_PLACE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_ISSUE_COUNTRY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MARITAL_STATUS_NAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CUST_REL_MARRIAGE_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RELIGION_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_BIRTH_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MEAL_DESC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NATIONALITY_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CITY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DESIGNATION_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CURRENCY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ALT_EMAIL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IS_ACCOUNT" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CREDIT_LIMIT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="USER_STATUS_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PARENT_CUSTORMER" Type="System.String" DbType="VarChar(306)" CanBeNull="true" />
      <Column Name="CHAIN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CHAIN_SR_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_CUST_CUSTOMER_CONTACT_DETAIL" Member="VIEW_CUST_CUSTOMER_CONTACT_DETAILs">
    <Type Name="VIEW_CUST_CUSTOMER_CONTACT_DETAIL">
      <Column Name="CUST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RELATION_DESC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CUST_REL_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SR_NO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS_TYPE_NAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CUST_ADDRESS_LINE1" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="CUST_ADDRESS_LINE2" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="CITY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COUNTRY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_PINCODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CUST_PHONE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMERGENCY_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CUST_MOBILE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WEBSITE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CHAIN_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VIDEO" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LOGO" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_CUST_CUSTOMER_MASTER" Member="VIEW_CUST_CUSTOMER_MASTERs">
    <Type Name="VIEW_CUST_CUSTOMER_MASTER">
      <Column Name="CUST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUST_UNQ_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TITLE_DESC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUST_SURNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CUST_REL_MOBILE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CUST_REL_EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CUST_TYPE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COMMUNICATION_MODE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COMMUNICATION_TIME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CUST_REL_PHONE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMPLOYEE" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="CUST_REL_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CUST_REL_SRNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RELATION_DESC" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CUST_COMPANY_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DESIGNATION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROFESSION_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GROUP_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREDIT_LIMIT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="CUST_REL_ANNUAL_INCOME" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_NO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_PRINTED_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_ISSUE_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_EXPIRY_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_ISSUE_PLACE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CUST_REL_PASSPORT_ISSUE_COUNTRY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACCOUNTING_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MARITAL_STATUS_NAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="CUST_REL_MARRIAGE_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RELIGION_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_BIRTH_DATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUST_CODE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_REL_GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MEAL_DESC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NATIONALITY_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CITY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DATE_LAST_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CURRENCY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IS_AGENT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PAYMENT_TERMS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DESIGNATION_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FIT_BOOKING_AMOUNT_IN_PECENTAGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CURRENT_USABLE_CREDIT_LIMIT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="BANK_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ACC_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BANK_BRNACH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GL_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BANK_CHARGES" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BANK_CHARGE_APPLICABLE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>