<?xml version="1.0" encoding="utf-8"?><Database Name="FULL_CRM_ASHISH" Class="CustomerTypeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVER;Initial Catalog=FULL_CRM_ASHISH;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_CUST_TYPE_MASTER" Member="VIEW_CUST_TYPE_MASTERs">
    <Type Name="VIEW_CUST_TYPE_MASTER">
      <Column Name="CUST_TYPE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUST_TYPE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CUST_TYPE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>