<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="DepartmentMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.5;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FULL_CRM_ASHISHConnectionString7" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_DEPARTMENT_MASTER" Member="VIEW_DEPARTMENT_MASTERs">
    <Type Name="VIEW_DEPARTMENT_MASTER">
      <Column Name="DEPARTMENT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEPARTMENT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEPARTMENT_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BIT_DELETED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>