<?xml version="1.0" encoding="utf-8"?><Database Name="thailand_new" Class="DesignationMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.11;Initial Catalog=thailand_new;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FULL_CRM_ASHISHConnectionString7" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_DESIGNATION_MASTER" Member="VIEW_DESIGNATION_MASTERs">
    <Type Name="VIEW_DESIGNATION_MASTER">
      <Column Name="DESIGNATION_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DESIGNATION_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BIT_DELETED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>