#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FULL_CRM_ASHISH")]
	public partial class EmailDbmlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EmailDbmlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmailDbmlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailDbmlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailDbmlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmailDbmlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_FOR_EMPLOYEE_EMAIL> VIEW_FOR_EMPLOYEE_EMAILs
		{
			get
			{
				return this.GetTable<VIEW_FOR_EMPLOYEE_EMAIL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_FOR_EMPLOYEE_EMAIL")]
	public partial class VIEW_FOR_EMPLOYEE_EMAIL
	{
		
		private string _EMP_NAME;
		
		private string _EMP_SURNAME;
		
		private string _TO_EMAIL;
		
		private string _USER_NAME;
		
		private string _DEPARTMENT_NAME;
		
		private string _REPORTING_TO;
		
		private string _FROM_EMAIL;
		
		public VIEW_FOR_EMPLOYEE_EMAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NAME", DbType="VarChar(50)")]
		public string EMP_NAME
		{
			get
			{
				return this._EMP_NAME;
			}
			set
			{
				if ((this._EMP_NAME != value))
				{
					this._EMP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_SURNAME", DbType="VarChar(50)")]
		public string EMP_SURNAME
		{
			get
			{
				return this._EMP_SURNAME;
			}
			set
			{
				if ((this._EMP_SURNAME != value))
				{
					this._EMP_SURNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_EMAIL", DbType="VarChar(50)")]
		public string TO_EMAIL
		{
			get
			{
				return this._TO_EMAIL;
			}
			set
			{
				if ((this._TO_EMAIL != value))
				{
					this._TO_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(50)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT_NAME", DbType="VarChar(50)")]
		public string DEPARTMENT_NAME
		{
			get
			{
				return this._DEPARTMENT_NAME;
			}
			set
			{
				if ((this._DEPARTMENT_NAME != value))
				{
					this._DEPARTMENT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTING_TO", DbType="VarChar(50)")]
		public string REPORTING_TO
		{
			get
			{
				return this._REPORTING_TO;
			}
			set
			{
				if ((this._REPORTING_TO != value))
				{
					this._REPORTING_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_EMAIL", DbType="VarChar(50)")]
		public string FROM_EMAIL
		{
			get
			{
				return this._FROM_EMAIL;
			}
			set
			{
				if ((this._FROM_EMAIL != value))
				{
					this._FROM_EMAIL = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
