<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="FromMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVERAI;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="THAILAND_CRMConnectionString5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FROM_MASTER_FOR_EMAIL" Member="FROM_MASTER_FOR_EMAILs">
    <Type Name="FROM_MASTER_FOR_EMAIL">
      <Column Name="FORM_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FORM_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FILE_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MODIFIED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>