#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FULL_CRM_ASHISH")]
	public partial class MarketingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MarketingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_MARKETING_CUSTOMER_NEW> VIEW_MARKETING_CUSTOMER_NEWs
		{
			get
			{
				return this.GetTable<VIEW_MARKETING_CUSTOMER_NEW>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_MARKETING_CUSTOMER_NEW")]
	public partial class VIEW_MARKETING_CUSTOMER_NEW
	{
		
		private int _MAR_DATA_ID;
		
		private string _MAR_DATA_SURNAME;
		
		private string _MAR_DATA_NAME;
		
		private string _ADDRESS_LINE_1;
		
		private string _ADDRESS_LINE_2;
		
		private string _MOBILE_NO;
		
		private string _PHONE_NO;
		
		private System.Nullable<System.DateTime> _DATE_CREATED;
		
		private System.Nullable<int> _CREATED_BY;
		
		private System.Nullable<System.DateTime> _DATE_MODIFIED;
		
		private System.Nullable<int> _MODIFIED_BY;
		
		private string _CITY_NAME;
		
		private string _STATE_NAME;
		
		private string _COUNTRY_NAME;
		
		private string _TITLE_DESC;
		
		private string _CUST_COMPANY_NAME;
		
		private string _COMMUNICATION_MODE_NAME;
		
		private System.Nullable<int> _TARGETLIST_ID;
		
		public VIEW_MARKETING_CUSTOMER_NEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAR_DATA_ID", DbType="Int NOT NULL")]
		public int MAR_DATA_ID
		{
			get
			{
				return this._MAR_DATA_ID;
			}
			set
			{
				if ((this._MAR_DATA_ID != value))
				{
					this._MAR_DATA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAR_DATA_SURNAME", DbType="VarChar(50)")]
		public string MAR_DATA_SURNAME
		{
			get
			{
				return this._MAR_DATA_SURNAME;
			}
			set
			{
				if ((this._MAR_DATA_SURNAME != value))
				{
					this._MAR_DATA_SURNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAR_DATA_NAME", DbType="VarChar(50)")]
		public string MAR_DATA_NAME
		{
			get
			{
				return this._MAR_DATA_NAME;
			}
			set
			{
				if ((this._MAR_DATA_NAME != value))
				{
					this._MAR_DATA_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_LINE_1", DbType="VarChar(200)")]
		public string ADDRESS_LINE_1
		{
			get
			{
				return this._ADDRESS_LINE_1;
			}
			set
			{
				if ((this._ADDRESS_LINE_1 != value))
				{
					this._ADDRESS_LINE_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_LINE_2", DbType="VarChar(200)")]
		public string ADDRESS_LINE_2
		{
			get
			{
				return this._ADDRESS_LINE_2;
			}
			set
			{
				if ((this._ADDRESS_LINE_2 != value))
				{
					this._ADDRESS_LINE_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE_NO", DbType="VarChar(10)")]
		public string MOBILE_NO
		{
			get
			{
				return this._MOBILE_NO;
			}
			set
			{
				if ((this._MOBILE_NO != value))
				{
					this._MOBILE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NO", DbType="VarChar(10)")]
		public string PHONE_NO
		{
			get
			{
				return this._PHONE_NO;
			}
			set
			{
				if ((this._PHONE_NO != value))
				{
					this._PHONE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this._DATE_CREATED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="Int")]
		public System.Nullable<int> CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this._CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_MODIFIED
		{
			get
			{
				return this._DATE_MODIFIED;
			}
			set
			{
				if ((this._DATE_MODIFIED != value))
				{
					this._DATE_MODIFIED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_BY", DbType="Int")]
		public System.Nullable<int> MODIFIED_BY
		{
			get
			{
				return this._MODIFIED_BY;
			}
			set
			{
				if ((this._MODIFIED_BY != value))
				{
					this._MODIFIED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_NAME", DbType="VarChar(50)")]
		public string CITY_NAME
		{
			get
			{
				return this._CITY_NAME;
			}
			set
			{
				if ((this._CITY_NAME != value))
				{
					this._CITY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_NAME", DbType="VarChar(50)")]
		public string STATE_NAME
		{
			get
			{
				return this._STATE_NAME;
			}
			set
			{
				if ((this._STATE_NAME != value))
				{
					this._STATE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_NAME", DbType="VarChar(50)")]
		public string COUNTRY_NAME
		{
			get
			{
				return this._COUNTRY_NAME;
			}
			set
			{
				if ((this._COUNTRY_NAME != value))
				{
					this._COUNTRY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE_DESC", DbType="VarChar(10)")]
		public string TITLE_DESC
		{
			get
			{
				return this._TITLE_DESC;
			}
			set
			{
				if ((this._TITLE_DESC != value))
				{
					this._TITLE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_COMPANY_NAME", DbType="VarChar(255)")]
		public string CUST_COMPANY_NAME
		{
			get
			{
				return this._CUST_COMPANY_NAME;
			}
			set
			{
				if ((this._CUST_COMPANY_NAME != value))
				{
					this._CUST_COMPANY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMUNICATION_MODE_NAME", DbType="VarChar(50)")]
		public string COMMUNICATION_MODE_NAME
		{
			get
			{
				return this._COMMUNICATION_MODE_NAME;
			}
			set
			{
				if ((this._COMMUNICATION_MODE_NAME != value))
				{
					this._COMMUNICATION_MODE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARGETLIST_ID", DbType="Int")]
		public System.Nullable<int> TARGETLIST_ID
		{
			get
			{
				return this._TARGETLIST_ID;
			}
			set
			{
				if ((this._TARGETLIST_ID != value))
				{
					this._TARGETLIST_ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
