#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FULL_CRM_ASHISH")]
	public partial class MarketingMaterialNewDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MarketingMaterialNewDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingMaterialNewDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingMaterialNewDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingMaterialNewDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketingMaterialNewDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_MARKETING_MATERIAL_NEW> VIEW_MARKETING_MATERIAL_NEWs
		{
			get
			{
				return this.GetTable<VIEW_MARKETING_MATERIAL_NEW>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_MARKETING_MATERIAL_NEW")]
	public partial class VIEW_MARKETING_MATERIAL_NEW
	{
		
		private int _MAR_ID;
		
		private System.Nullable<int> _TOUR_ID;
		
		private string _TOUR_SHORT_NAME;
		
		private string _TOUR_CODE;
		
		public VIEW_MARKETING_MATERIAL_NEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAR_ID", DbType="Int NOT NULL")]
		public int MAR_ID
		{
			get
			{
				return this._MAR_ID;
			}
			set
			{
				if ((this._MAR_ID != value))
				{
					this._MAR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int")]
		public System.Nullable<int> TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_SHORT_NAME", DbType="VarChar(50)")]
		public string TOUR_SHORT_NAME
		{
			get
			{
				return this._TOUR_SHORT_NAME;
			}
			set
			{
				if ((this._TOUR_SHORT_NAME != value))
				{
					this._TOUR_SHORT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_CODE", DbType="VarChar(50)")]
		public string TOUR_CODE
		{
			get
			{
				return this._TOUR_CODE;
			}
			set
			{
				if ((this._TOUR_CODE != value))
				{
					this._TOUR_CODE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
