<?xml version="1.0" encoding="utf-8"?><Database Name="FULL_CRM_ASHISH" Class="MarketingMaterialNewDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.12;Initial Catalog=FULL_CRM_ASHISH;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_MARKETING_MATERIAL_NEW" Member="VIEW_MARKETING_MATERIAL_NEWs">
    <Type Name="VIEW_MARKETING_MATERIAL_NEW">
      <Column Name="MAR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TOUR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOUR_SHORT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TOUR_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>