<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="NewEmployeeDbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVERAI;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.COMPANY_MASTER" Member="COMPANY_MASTERs">
    <Type Name="COMPANY_MASTER">
      <Column Name="COMPANY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="COMPANY_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_ROLE_MASTER" Member="SYS_ROLE_MASTERs">
    <Type Name="SYS_ROLE_MASTER">
      <Column Name="ROLE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ROLE_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_COMPANY_OF_EMPLOYEE_NEW" Member="VIEW_COMPANY_OF_EMPLOYEE_NEWs">
    <Type Name="VIEW_COMPANY_OF_EMPLOYEE_NEW">
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COMPANY_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="COMPANY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_ROLE_MASTER_NEW" Member="VIEW_ROLE_MASTER_NEWs">
    <Type Name="VIEW_ROLE_MASTER_NEW">
      <Column Name="ROLE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ROLE_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_CONTACT_DETAIL_FOR_EMPLOYEE" Member="VIEW_CONTACT_DETAIL_FOR_EMPLOYEEs">
    <Type Name="VIEW_CONTACT_DETAIL_FOR_EMPLOYEE">
      <Column Name="ADDRESS_LINE1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ADDRESS_LINE2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PINCODE" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_CONTACT_SRNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNTRY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CITY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADDRESS_TYPE_NAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_USER_MASTER_FOR_EMPLOYEE" Member="VIEW_USER_MASTER_FOR_EMPLOYEEs">
    <Type Name="VIEW_USER_MASTER_FOR_EMPLOYEE">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USER_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EMP_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_FULL_NAME" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="SECURITY_QUESTION_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SECURITY_QUESTION_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SECURITY_ANSWERS" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FROM_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TO_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIED_BY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_EMPLOYEE_MASTER_NEW" Member="VIEW_EMPLOYEE_MASTER_NEWs">
    <Type Name="VIEW_EMPLOYEE_MASTER_NEW">
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EMP_TITLE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TITLE_DESC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EMP_SURNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_DOB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EMP_MARITAL_STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MARITAL_DATA" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="EMP_GENDER" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EMP_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_MOBILE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="EMP_PHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_QUALIFICATION_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUALIFICATION_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_NAME" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SIGNATURE_PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SIGNATURE1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REPORTING_TO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMPLOYEE_SALARY" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIEW_EMP_ROLE_MAPPING" Member="VIEW_EMP_ROLE_MAPPINGs">
    <Type Name="VIEW_EMP_ROLE_MAPPING">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COMPANY_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ROLE_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DEPARTMENT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPORTING_TO" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
    </Type>
  </Table>
</Database>