<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="NewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVERAI;Initial Catalog=THAILAND_CRM;User ID=SA" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="THAILAND_CRMConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_NEWS_MASTER" Member="VIEW_NEWS_MASTERs">
    <Type Name="VIEW_NEWS_MASTER">
      <Column Name="NEWS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NEWS_HEADER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEWS_DESCRIPTION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DISPLAY_ON_DASHBOARD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>