#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THAILAND_CRM")]
	public partial class ProgramMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ProgramMasterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FULL_CRM_ASHISHConnectionString4"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProgramMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgramMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgramMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgramMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_FOR_DEPT_ROLE_GRID> VIEW_FOR_DEPT_ROLE_GRIDs
		{
			get
			{
				return this.GetTable<VIEW_FOR_DEPT_ROLE_GRID>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_SUB_PROGRAM_ACCESS_GRID> VIEW_SUB_PROGRAM_ACCESS_GRIDs
		{
			get
			{
				return this.GetTable<VIEW_SUB_PROGRAM_ACCESS_GRID>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_PROGRAM_MASTER> VIEW_PROGRAM_MASTERs
		{
			get
			{
				return this.GetTable<VIEW_PROGRAM_MASTER>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_PROGRAM_ACCESS_GRID> VIEW_PROGRAM_ACCESS_GRIDs
		{
			get
			{
				return this.GetTable<VIEW_PROGRAM_ACCESS_GRID>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_SUB_PROGRAM_MASTER_NEW> VIEW_SUB_PROGRAM_MASTER_NEWs
		{
			get
			{
				return this.GetTable<VIEW_SUB_PROGRAM_MASTER_NEW>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_FOR_DEPT_ROLE_GRID")]
	public partial class VIEW_FOR_DEPT_ROLE_GRID
	{
		
		private string _DEPT_NAME;
		
		private string _ROLE;
		
		private int _ROLE_ID;
		
		private System.Nullable<int> _DEPT_ID;
		
		private string _COMPANY_NAME;
		
		private int _COMPANY_ID;
		
		public VIEW_FOR_DEPT_ROLE_GRID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_NAME", DbType="VarChar(50)")]
		public string DEPT_NAME
		{
			get
			{
				return this._DEPT_NAME;
			}
			set
			{
				if ((this._DEPT_NAME != value))
				{
					this._DEPT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="NVarChar(50)")]
		public string ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this._ROLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_ID", DbType="Int NOT NULL")]
		public int ROLE_ID
		{
			get
			{
				return this._ROLE_ID;
			}
			set
			{
				if ((this._ROLE_ID != value))
				{
					this._ROLE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_ID", DbType="Int")]
		public System.Nullable<int> DEPT_ID
		{
			get
			{
				return this._DEPT_ID;
			}
			set
			{
				if ((this._DEPT_ID != value))
				{
					this._DEPT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(100)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this._COMPANY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_ID", DbType="Int NOT NULL")]
		public int COMPANY_ID
		{
			get
			{
				return this._COMPANY_ID;
			}
			set
			{
				if ((this._COMPANY_ID != value))
				{
					this._COMPANY_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_SUB_PROGRAM_ACCESS_GRID")]
	public partial class VIEW_SUB_PROGRAM_ACCESS_GRID
	{
		
		private int _ROLE_ID;
		
		private int _SUB_PROGRAM_ID;
		
		private int _DEPT_ID;
		
		private string _READ_ACCESS;
		
		private string _WRITE_ACCESS;
		
		private string _DELETE_ACCESS;
		
		private string _PRINT_ACCESS;
		
		private string _PROGRAM_SUB_NAME;
		
		private System.Nullable<int> _COMPANY_ID;
		
		public VIEW_SUB_PROGRAM_ACCESS_GRID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_ID", DbType="Int NOT NULL")]
		public int ROLE_ID
		{
			get
			{
				return this._ROLE_ID;
			}
			set
			{
				if ((this._ROLE_ID != value))
				{
					this._ROLE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_PROGRAM_ID", DbType="Int NOT NULL")]
		public int SUB_PROGRAM_ID
		{
			get
			{
				return this._SUB_PROGRAM_ID;
			}
			set
			{
				if ((this._SUB_PROGRAM_ID != value))
				{
					this._SUB_PROGRAM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_ID", DbType="Int NOT NULL")]
		public int DEPT_ID
		{
			get
			{
				return this._DEPT_ID;
			}
			set
			{
				if ((this._DEPT_ID != value))
				{
					this._DEPT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_READ_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string READ_ACCESS
		{
			get
			{
				return this._READ_ACCESS;
			}
			set
			{
				if ((this._READ_ACCESS != value))
				{
					this._READ_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WRITE_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string WRITE_ACCESS
		{
			get
			{
				return this._WRITE_ACCESS;
			}
			set
			{
				if ((this._WRITE_ACCESS != value))
				{
					this._WRITE_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETE_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string DELETE_ACCESS
		{
			get
			{
				return this._DELETE_ACCESS;
			}
			set
			{
				if ((this._DELETE_ACCESS != value))
				{
					this._DELETE_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINT_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PRINT_ACCESS
		{
			get
			{
				return this._PRINT_ACCESS;
			}
			set
			{
				if ((this._PRINT_ACCESS != value))
				{
					this._PRINT_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_SUB_NAME", DbType="VarChar(200)")]
		public string PROGRAM_SUB_NAME
		{
			get
			{
				return this._PROGRAM_SUB_NAME;
			}
			set
			{
				if ((this._PROGRAM_SUB_NAME != value))
				{
					this._PROGRAM_SUB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_ID", DbType="Int")]
		public System.Nullable<int> COMPANY_ID
		{
			get
			{
				return this._COMPANY_ID;
			}
			set
			{
				if ((this._COMPANY_ID != value))
				{
					this._COMPANY_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_PROGRAM_MASTER")]
	public partial class VIEW_PROGRAM_MASTER
	{
		
		private int _PROGRAM_ID;
		
		private string _PROGRAM_NAME;
		
		private string _PROGRAM_TEXT;
		
		private string _PROGRAM_ACCESS_KEY;
		
		private System.Nullable<int> _PROGRAM_SORT_ORDER;
		
		private string _MODULE_NAME;
		
		private string _PROGRAM_TYPE_NAME;
		
		public VIEW_PROGRAM_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ID", DbType="Int NOT NULL")]
		public int PROGRAM_ID
		{
			get
			{
				return this._PROGRAM_ID;
			}
			set
			{
				if ((this._PROGRAM_ID != value))
				{
					this._PROGRAM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_NAME", DbType="VarChar(255)")]
		public string PROGRAM_NAME
		{
			get
			{
				return this._PROGRAM_NAME;
			}
			set
			{
				if ((this._PROGRAM_NAME != value))
				{
					this._PROGRAM_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_TEXT", DbType="VarChar(50)")]
		public string PROGRAM_TEXT
		{
			get
			{
				return this._PROGRAM_TEXT;
			}
			set
			{
				if ((this._PROGRAM_TEXT != value))
				{
					this._PROGRAM_TEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ACCESS_KEY", DbType="VarChar(1)")]
		public string PROGRAM_ACCESS_KEY
		{
			get
			{
				return this._PROGRAM_ACCESS_KEY;
			}
			set
			{
				if ((this._PROGRAM_ACCESS_KEY != value))
				{
					this._PROGRAM_ACCESS_KEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_SORT_ORDER", DbType="Int")]
		public System.Nullable<int> PROGRAM_SORT_ORDER
		{
			get
			{
				return this._PROGRAM_SORT_ORDER;
			}
			set
			{
				if ((this._PROGRAM_SORT_ORDER != value))
				{
					this._PROGRAM_SORT_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(50)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this._MODULE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_TYPE_NAME", DbType="VarChar(50)")]
		public string PROGRAM_TYPE_NAME
		{
			get
			{
				return this._PROGRAM_TYPE_NAME;
			}
			set
			{
				if ((this._PROGRAM_TYPE_NAME != value))
				{
					this._PROGRAM_TYPE_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_PROGRAM_ACCESS_GRID")]
	public partial class VIEW_PROGRAM_ACCESS_GRID
	{
		
		private string _PROG_NAME;
		
		private string _READ_ACCESS;
		
		private string _WRITE_ACCESS;
		
		private string _DELETE_ACCESS;
		
		private string _PRINT_ACCESS;
		
		private int _ROLE_ID;
		
		private System.Nullable<int> _DEPT_ID;
		
		private int _PROGRAM_ID;
		
		private System.Nullable<int> _COMPANY_ID;
		
		private string _CUST_TYPE;
		
		private string _CHANGE_CUST_OWNER;
		
		private System.Nullable<decimal> _TOUR_DISCOUNT;
		
		private System.Nullable<decimal> _TICKETING_DISCOUNT;
		
		private System.Nullable<decimal> _VISA_DISCOUNT;
		
		public VIEW_PROGRAM_ACCESS_GRID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_NAME", DbType="VarChar(50)")]
		public string PROG_NAME
		{
			get
			{
				return this._PROG_NAME;
			}
			set
			{
				if ((this._PROG_NAME != value))
				{
					this._PROG_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_READ_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string READ_ACCESS
		{
			get
			{
				return this._READ_ACCESS;
			}
			set
			{
				if ((this._READ_ACCESS != value))
				{
					this._READ_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WRITE_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string WRITE_ACCESS
		{
			get
			{
				return this._WRITE_ACCESS;
			}
			set
			{
				if ((this._WRITE_ACCESS != value))
				{
					this._WRITE_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETE_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string DELETE_ACCESS
		{
			get
			{
				return this._DELETE_ACCESS;
			}
			set
			{
				if ((this._DELETE_ACCESS != value))
				{
					this._DELETE_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINT_ACCESS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PRINT_ACCESS
		{
			get
			{
				return this._PRINT_ACCESS;
			}
			set
			{
				if ((this._PRINT_ACCESS != value))
				{
					this._PRINT_ACCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_ID", DbType="Int NOT NULL")]
		public int ROLE_ID
		{
			get
			{
				return this._ROLE_ID;
			}
			set
			{
				if ((this._ROLE_ID != value))
				{
					this._ROLE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_ID", DbType="Int")]
		public System.Nullable<int> DEPT_ID
		{
			get
			{
				return this._DEPT_ID;
			}
			set
			{
				if ((this._DEPT_ID != value))
				{
					this._DEPT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ID", DbType="Int NOT NULL")]
		public int PROGRAM_ID
		{
			get
			{
				return this._PROGRAM_ID;
			}
			set
			{
				if ((this._PROGRAM_ID != value))
				{
					this._PROGRAM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_ID", DbType="Int")]
		public System.Nullable<int> COMPANY_ID
		{
			get
			{
				return this._COMPANY_ID;
			}
			set
			{
				if ((this._COMPANY_ID != value))
				{
					this._COMPANY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_TYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string CUST_TYPE
		{
			get
			{
				return this._CUST_TYPE;
			}
			set
			{
				if ((this._CUST_TYPE != value))
				{
					this._CUST_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_CUST_OWNER", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string CHANGE_CUST_OWNER
		{
			get
			{
				return this._CHANGE_CUST_OWNER;
			}
			set
			{
				if ((this._CHANGE_CUST_OWNER != value))
				{
					this._CHANGE_CUST_OWNER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_DISCOUNT", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> TOUR_DISCOUNT
		{
			get
			{
				return this._TOUR_DISCOUNT;
			}
			set
			{
				if ((this._TOUR_DISCOUNT != value))
				{
					this._TOUR_DISCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TICKETING_DISCOUNT", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> TICKETING_DISCOUNT
		{
			get
			{
				return this._TICKETING_DISCOUNT;
			}
			set
			{
				if ((this._TICKETING_DISCOUNT != value))
				{
					this._TICKETING_DISCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISA_DISCOUNT", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> VISA_DISCOUNT
		{
			get
			{
				return this._VISA_DISCOUNT;
			}
			set
			{
				if ((this._VISA_DISCOUNT != value))
				{
					this._VISA_DISCOUNT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_SUB_PROGRAM_MASTER_NEW")]
	public partial class VIEW_SUB_PROGRAM_MASTER_NEW
	{
		
		private int _PROGRAM_SUB_ID;
		
		private System.Nullable<int> _PARENT_ID;
		
		private string _PROGRAM_SUB_NAME;
		
		private System.Nullable<int> _PROGRAM_ID;
		
		private string _PARENT_NAME;
		
		private string _NEWPROGRAM_TEXT;
		
		private System.Nullable<int> _PROGRAM;
		
		public VIEW_SUB_PROGRAM_MASTER_NEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_SUB_ID", DbType="Int NOT NULL")]
		public int PROGRAM_SUB_ID
		{
			get
			{
				return this._PROGRAM_SUB_ID;
			}
			set
			{
				if ((this._PROGRAM_SUB_ID != value))
				{
					this._PROGRAM_SUB_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Int")]
		public System.Nullable<int> PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_SUB_NAME", DbType="VarChar(200)")]
		public string PROGRAM_SUB_NAME
		{
			get
			{
				return this._PROGRAM_SUB_NAME;
			}
			set
			{
				if ((this._PROGRAM_SUB_NAME != value))
				{
					this._PROGRAM_SUB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ID", DbType="Int")]
		public System.Nullable<int> PROGRAM_ID
		{
			get
			{
				return this._PROGRAM_ID;
			}
			set
			{
				if ((this._PROGRAM_ID != value))
				{
					this._PROGRAM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_NAME", DbType="VarChar(200)")]
		public string PARENT_NAME
		{
			get
			{
				return this._PARENT_NAME;
			}
			set
			{
				if ((this._PARENT_NAME != value))
				{
					this._PARENT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEWPROGRAM_TEXT", DbType="VarChar(50)")]
		public string NEWPROGRAM_TEXT
		{
			get
			{
				return this._NEWPROGRAM_TEXT;
			}
			set
			{
				if ((this._NEWPROGRAM_TEXT != value))
				{
					this._NEWPROGRAM_TEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM", DbType="Int")]
		public System.Nullable<int> PROGRAM
		{
			get
			{
				return this._PROGRAM;
			}
			set
			{
				if ((this._PROGRAM != value))
				{
					this._PROGRAM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
