#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THAILAND_CRM")]
	public partial class SideCodeMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SideCodeMasterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["THAILAND_CRMConnectionString3"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SideCodeMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SideCodeMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SideCodeMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SideCodeMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_SIDE_CODE_MASTER> VIEW_SIDE_CODE_MASTERs
		{
			get
			{
				return this.GetTable<VIEW_SIDE_CODE_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_SIDE_CODE_MASTER")]
	public partial class VIEW_SIDE_CODE_MASTER
	{
		
		private int _SIDE_CODE_ID;
		
		private string _SIDE_CODE_NAME;
		
		public VIEW_SIDE_CODE_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIDE_CODE_ID", DbType="Int NOT NULL")]
		public int SIDE_CODE_ID
		{
			get
			{
				return this._SIDE_CODE_ID;
			}
			set
			{
				if ((this._SIDE_CODE_ID != value))
				{
					this._SIDE_CODE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIDE_CODE_NAME", DbType="VarChar(50)")]
		public string SIDE_CODE_NAME
		{
			get
			{
				return this._SIDE_CODE_NAME;
			}
			set
			{
				if ((this._SIDE_CODE_NAME != value))
				{
					this._SIDE_CODE_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
