<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="SideCodeMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVER;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="THAILAND_CRMConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_SIDE_CODE_MASTER" Member="VIEW_SIDE_CODE_MASTERs">
    <Type Name="VIEW_SIDE_CODE_MASTER">
      <Column Name="SIDE_CODE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SIDE_CODE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>