#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THAILAND_CRM")]
	public partial class SpecialOfferDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SpecialOfferDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["THAILAND_CRMConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SpecialOfferDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SpecialOfferDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SpecialOfferDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SpecialOfferDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_SPECIAL_OFFER> VIEW_SPECIAL_OFFERs
		{
			get
			{
				return this.GetTable<VIEW_SPECIAL_OFFER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_SPECIAL_OFFER")]
	public partial class VIEW_SPECIAL_OFFER
	{
		
		private int _OFFER_ID;
		
		private string _PACKAGE_NAME;
		
		private System.Nullable<decimal> _PRICE;
		
		private string _CURRENCY;
		
		private string _DISPLAY_ON_DASHBOARD;
		
		public VIEW_SPECIAL_OFFER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_ID", DbType="Int NOT NULL")]
		public int OFFER_ID
		{
			get
			{
				return this._OFFER_ID;
			}
			set
			{
				if ((this._OFFER_ID != value))
				{
					this._OFFER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKAGE_NAME", DbType="VarChar(MAX)")]
		public string PACKAGE_NAME
		{
			get
			{
				return this._PACKAGE_NAME;
			}
			set
			{
				if ((this._PACKAGE_NAME != value))
				{
					this._PACKAGE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this._PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCY", DbType="VarChar(50)")]
		public string CURRENCY
		{
			get
			{
				return this._CURRENCY;
			}
			set
			{
				if ((this._CURRENCY != value))
				{
					this._CURRENCY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPLAY_ON_DASHBOARD", DbType="VarChar(50)")]
		public string DISPLAY_ON_DASHBOARD
		{
			get
			{
				return this._DISPLAY_ON_DASHBOARD;
			}
			set
			{
				if ((this._DISPLAY_ON_DASHBOARD != value))
				{
					this._DISPLAY_ON_DASHBOARD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
