<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="SupplierMarginMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.13;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_SUPPLIER_MARGIN_MASTER" Member="VIEW_SUPPLIER_MARGIN_MASTERs">
    <Type Name="VIEW_SUPPLIER_MARGIN_MASTER">
      <Column Name="SUPPLIER_MARGIN_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUPPLIER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MARGIN_AMOUNT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="MARGIN_AMOUNT_IN_PERCENTAGE" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="SUPPLIER_COMPANY_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PRODUCT_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>