#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THAILAND_CRM")]
	public partial class SupplierCoachPriceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SupplierCoachPriceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["THAILAND_CRMConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierCoachPriceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierCoachPriceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierCoachPriceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierCoachPriceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_SUPPLIER_COACH_PRICE_LIST> VIEW_SUPPLIER_COACH_PRICE_LISTs
		{
			get
			{
				return this.GetTable<VIEW_SUPPLIER_COACH_PRICE_LIST>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_SUPPLIER_COACH_PRICE_LIST")]
	public partial class VIEW_SUPPLIER_COACH_PRICE_LIST
	{
		
		private int _COACH_PRICE_LIST_ID;
		
		private System.Nullable<int> _SUPPLIER_SR_NO;
		
		private string _COACH_NAME;
		
		private string _EFFECTIVE_FROM_DATE;
		
		private string _EFFECTIVE_TO_DATE;
		
		private System.Nullable<int> _NO_OF_SEATS;
		
		private System.Nullable<decimal> _GIT_RATE;
		
		private System.Nullable<decimal> _FIT_RATE;
		
		private System.Nullable<decimal> _FIT_DISCOUNT;
		
		private System.Nullable<decimal> _GIT_DISCOUNT;
		
		private System.Nullable<decimal> _MARGIN_AMOUNT;
		
		private System.Nullable<decimal> _MARGIN_AMOUNT_IN_PERCENTAGE;
		
		private string _CURRENCY_NAME;
		
		private System.Nullable<int> _CUST_ID;
		
		private string _CUSTOMER_NAME;
		
		private string _PAYMENT_TERMS;
		
		private string _SUPPLIER_NAME;
		
		private System.Nullable<decimal> _GIT_MARGIN_AMOUNT;
		
		private System.Nullable<decimal> _GIT_MARGIN_AMOUNT_IN_PERCENTAGE;
		
		private string _CITY_NAME;
		
		private string _FROM_DATE;
		
		private string _TO_DATE;
		
		public VIEW_SUPPLIER_COACH_PRICE_LIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COACH_PRICE_LIST_ID", DbType="Int NOT NULL")]
		public int COACH_PRICE_LIST_ID
		{
			get
			{
				return this._COACH_PRICE_LIST_ID;
			}
			set
			{
				if ((this._COACH_PRICE_LIST_ID != value))
				{
					this._COACH_PRICE_LIST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPLIER_SR_NO", DbType="Int")]
		public System.Nullable<int> SUPPLIER_SR_NO
		{
			get
			{
				return this._SUPPLIER_SR_NO;
			}
			set
			{
				if ((this._SUPPLIER_SR_NO != value))
				{
					this._SUPPLIER_SR_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COACH_NAME", DbType="VarChar(50)")]
		public string COACH_NAME
		{
			get
			{
				return this._COACH_NAME;
			}
			set
			{
				if ((this._COACH_NAME != value))
				{
					this._COACH_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFECTIVE_FROM_DATE", DbType="VarChar(10)")]
		public string EFFECTIVE_FROM_DATE
		{
			get
			{
				return this._EFFECTIVE_FROM_DATE;
			}
			set
			{
				if ((this._EFFECTIVE_FROM_DATE != value))
				{
					this._EFFECTIVE_FROM_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFECTIVE_TO_DATE", DbType="VarChar(10)")]
		public string EFFECTIVE_TO_DATE
		{
			get
			{
				return this._EFFECTIVE_TO_DATE;
			}
			set
			{
				if ((this._EFFECTIVE_TO_DATE != value))
				{
					this._EFFECTIVE_TO_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_SEATS", DbType="Int")]
		public System.Nullable<int> NO_OF_SEATS
		{
			get
			{
				return this._NO_OF_SEATS;
			}
			set
			{
				if ((this._NO_OF_SEATS != value))
				{
					this._NO_OF_SEATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIT_RATE", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> GIT_RATE
		{
			get
			{
				return this._GIT_RATE;
			}
			set
			{
				if ((this._GIT_RATE != value))
				{
					this._GIT_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIT_RATE", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> FIT_RATE
		{
			get
			{
				return this._FIT_RATE;
			}
			set
			{
				if ((this._FIT_RATE != value))
				{
					this._FIT_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIT_DISCOUNT", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> FIT_DISCOUNT
		{
			get
			{
				return this._FIT_DISCOUNT;
			}
			set
			{
				if ((this._FIT_DISCOUNT != value))
				{
					this._FIT_DISCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIT_DISCOUNT", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> GIT_DISCOUNT
		{
			get
			{
				return this._GIT_DISCOUNT;
			}
			set
			{
				if ((this._GIT_DISCOUNT != value))
				{
					this._GIT_DISCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARGIN_AMOUNT", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> MARGIN_AMOUNT
		{
			get
			{
				return this._MARGIN_AMOUNT;
			}
			set
			{
				if ((this._MARGIN_AMOUNT != value))
				{
					this._MARGIN_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARGIN_AMOUNT_IN_PERCENTAGE", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> MARGIN_AMOUNT_IN_PERCENTAGE
		{
			get
			{
				return this._MARGIN_AMOUNT_IN_PERCENTAGE;
			}
			set
			{
				if ((this._MARGIN_AMOUNT_IN_PERCENTAGE != value))
				{
					this._MARGIN_AMOUNT_IN_PERCENTAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCY_NAME", DbType="VarChar(50)")]
		public string CURRENCY_NAME
		{
			get
			{
				return this._CURRENCY_NAME;
			}
			set
			{
				if ((this._CURRENCY_NAME != value))
				{
					this._CURRENCY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ID", DbType="Int")]
		public System.Nullable<int> CUST_ID
		{
			get
			{
				return this._CUST_ID;
			}
			set
			{
				if ((this._CUST_ID != value))
				{
					this._CUST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(307)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT_TERMS", DbType="VarChar(50)")]
		public string PAYMENT_TERMS
		{
			get
			{
				return this._PAYMENT_TERMS;
			}
			set
			{
				if ((this._PAYMENT_TERMS != value))
				{
					this._PAYMENT_TERMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPLIER_NAME", DbType="VarChar(MAX)")]
		public string SUPPLIER_NAME
		{
			get
			{
				return this._SUPPLIER_NAME;
			}
			set
			{
				if ((this._SUPPLIER_NAME != value))
				{
					this._SUPPLIER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIT_MARGIN_AMOUNT", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> GIT_MARGIN_AMOUNT
		{
			get
			{
				return this._GIT_MARGIN_AMOUNT;
			}
			set
			{
				if ((this._GIT_MARGIN_AMOUNT != value))
				{
					this._GIT_MARGIN_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIT_MARGIN_AMOUNT_IN_PERCENTAGE", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> GIT_MARGIN_AMOUNT_IN_PERCENTAGE
		{
			get
			{
				return this._GIT_MARGIN_AMOUNT_IN_PERCENTAGE;
			}
			set
			{
				if ((this._GIT_MARGIN_AMOUNT_IN_PERCENTAGE != value))
				{
					this._GIT_MARGIN_AMOUNT_IN_PERCENTAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_NAME", DbType="VarChar(50)")]
		public string CITY_NAME
		{
			get
			{
				return this._CITY_NAME;
			}
			set
			{
				if ((this._CITY_NAME != value))
				{
					this._CITY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_DATE", DbType="VarChar(10)")]
		public string FROM_DATE
		{
			get
			{
				return this._FROM_DATE;
			}
			set
			{
				if ((this._FROM_DATE != value))
				{
					this._FROM_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_DATE", DbType="VarChar(10)")]
		public string TO_DATE
		{
			get
			{
				return this._TO_DATE;
			}
			set
			{
				if ((this._TO_DATE != value))
				{
					this._TO_DATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
