<?xml version="1.0" encoding="utf-8"?><Database Name="THAILAND_CRM" Class="SupplierFacilityMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.13;Initial Catalog=THAILAND_CRM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_SUPPLIER_FACALITY_MASTER" Member="VIEW_SUPPLIER_FACALITY_MASTERs">
    <Type Name="VIEW_SUPPLIER_FACALITY_MASTER">
      <Column Name="FACELITY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUPPLIER_SR_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUPPLIER_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FACILITY_DISCRIPTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>