#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THAILAND_CRM")]
	public partial class SupplierLandmarkMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SupplierLandmarkMasterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierLandmarkMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierLandmarkMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierLandmarkMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SupplierLandmarkMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VIEW_SUPPLIER_LANDMARK_MASTER> VIEW_SUPPLIER_LANDMARK_MASTERs
		{
			get
			{
				return this.GetTable<VIEW_SUPPLIER_LANDMARK_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_SUPPLIER_LANDMARK_MASTER")]
	public partial class VIEW_SUPPLIER_LANDMARK_MASTER
	{
		
		private int _LANDMARK_ID;
		
		private System.Nullable<int> _SUPPLIER_SR_NO;
		
		private string _LANDMARK_DESC;
		
		private System.Nullable<System.DateTime> _DATE_CREATED;
		
		private System.Nullable<int> _CREATED_BY;
		
		private System.Nullable<System.DateTime> _DATE_MODIFIED;
		
		private System.Nullable<int> _MODIFIED_BY;
		
		private string _GOOGLE_MAP_CODE;
		
		private string _SUPPLIER_NAME;
		
		public VIEW_SUPPLIER_LANDMARK_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDMARK_ID", DbType="Int NOT NULL")]
		public int LANDMARK_ID
		{
			get
			{
				return this._LANDMARK_ID;
			}
			set
			{
				if ((this._LANDMARK_ID != value))
				{
					this._LANDMARK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPLIER_SR_NO", DbType="Int")]
		public System.Nullable<int> SUPPLIER_SR_NO
		{
			get
			{
				return this._SUPPLIER_SR_NO;
			}
			set
			{
				if ((this._SUPPLIER_SR_NO != value))
				{
					this._SUPPLIER_SR_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDMARK_DESC", DbType="VarChar(50)")]
		public string LANDMARK_DESC
		{
			get
			{
				return this._LANDMARK_DESC;
			}
			set
			{
				if ((this._LANDMARK_DESC != value))
				{
					this._LANDMARK_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this._DATE_CREATED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="Int")]
		public System.Nullable<int> CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this._CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_MODIFIED
		{
			get
			{
				return this._DATE_MODIFIED;
			}
			set
			{
				if ((this._DATE_MODIFIED != value))
				{
					this._DATE_MODIFIED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_BY", DbType="Int")]
		public System.Nullable<int> MODIFIED_BY
		{
			get
			{
				return this._MODIFIED_BY;
			}
			set
			{
				if ((this._MODIFIED_BY != value))
				{
					this._MODIFIED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOOGLE_MAP_CODE", DbType="VarChar(50)")]
		public string GOOGLE_MAP_CODE
		{
			get
			{
				return this._GOOGLE_MAP_CODE;
			}
			set
			{
				if ((this._GOOGLE_MAP_CODE != value))
				{
					this._GOOGLE_MAP_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPLIER_NAME", DbType="VarChar(MAX)")]
		public string SUPPLIER_NAME
		{
			get
			{
				return this._SUPPLIER_NAME;
			}
			set
			{
				if ((this._SUPPLIER_NAME != value))
				{
					this._SUPPLIER_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
