#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.WebApp.Views.dbmlfile
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FULL_CRM_ASHISH")]
	public partial class TourMasterDataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOMMON_MARKETING_MATERIAL(COMMON_MARKETING_MATERIAL instance);
    partial void UpdateCOMMON_MARKETING_MATERIAL(COMMON_MARKETING_MATERIAL instance);
    partial void DeleteCOMMON_MARKETING_MATERIAL(COMMON_MARKETING_MATERIAL instance);
    partial void InsertTOUR_QUOTE_MASTER(TOUR_QUOTE_MASTER instance);
    partial void UpdateTOUR_QUOTE_MASTER(TOUR_QUOTE_MASTER instance);
    partial void DeleteTOUR_QUOTE_MASTER(TOUR_QUOTE_MASTER instance);
    #endregion
		
		public TourMasterDataBaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRM"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TourMasterDataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TourMasterDataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TourMasterDataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TourMasterDataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COMMON_MARKETING_MATERIAL> COMMON_MARKETING_MATERIALs
		{
			get
			{
				return this.GetTable<COMMON_MARKETING_MATERIAL>();
			}
		}
		
		public System.Data.Linq.Table<TOUR_QUOTE_MASTER> TOUR_QUOTE_MASTERs
		{
			get
			{
				return this.GetTable<TOUR_QUOTE_MASTER>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_TOUR_TRANSPORTATION_DETAIL> VIEW_TOUR_TRANSPORTATION_DETAILs
		{
			get
			{
				return this.GetTable<VIEW_TOUR_TRANSPORTATION_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_DECK_CABINE_DETAIL> VIEW_DECK_CABINE_DETAILs
		{
			get
			{
				return this.GetTable<VIEW_DECK_CABINE_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_COUNTRY_FOR_VISA> VIEW_COUNTRY_FOR_VISAs
		{
			get
			{
				return this.GetTable<VIEW_COUNTRY_FOR_VISA>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_TOUR_MASTER> VIEW_TOUR_MASTERs
		{
			get
			{
				return this.GetTable<VIEW_TOUR_MASTER>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_CRUISE_DETAIL> VIEW_CRUISE_DETAILs
		{
			get
			{
				return this.GetTable<VIEW_CRUISE_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_FLIGHT_DETAIL> VIEW_FLIGHT_DETAILs
		{
			get
			{
				return this.GetTable<VIEW_FLIGHT_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<VIEW_TOUR_HOTEL_DETAIL> VIEW_TOUR_HOTEL_DETAILs
		{
			get
			{
				return this.GetTable<VIEW_TOUR_HOTEL_DETAIL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMMON_MARKETING_MATERIAL")]
	public partial class COMMON_MARKETING_MATERIAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAR_ID;
		
		private int _TOUR_ID;
		
		private string _TITLE;
		
		private string _TYPE;
		
		private System.Nullable<System.DateTime> _EXPIRATION_DATE;
		
		private string _DESCRIPTION;
		
		private string _ATTACHMENT;
		
		private string _EMBEDCODE;
		
		private string _WEBURL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAR_IDChanging(int value);
    partial void OnMAR_IDChanged();
    partial void OnTOUR_IDChanging(int value);
    partial void OnTOUR_IDChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnEXPIRATION_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEXPIRATION_DATEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnATTACHMENTChanging(string value);
    partial void OnATTACHMENTChanged();
    partial void OnEMBEDCODEChanging(string value);
    partial void OnEMBEDCODEChanged();
    partial void OnWEBURLChanging(string value);
    partial void OnWEBURLChanged();
    #endregion
		
		public COMMON_MARKETING_MATERIAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAR_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAR_ID
		{
			get
			{
				return this._MAR_ID;
			}
			set
			{
				if ((this._MAR_ID != value))
				{
					this.OnMAR_IDChanging(value);
					this.SendPropertyChanging();
					this._MAR_ID = value;
					this.SendPropertyChanged("MAR_ID");
					this.OnMAR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int NOT NULL")]
		public int TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this.OnTOUR_IDChanging(value);
					this.SendPropertyChanging();
					this._TOUR_ID = value;
					this.SendPropertyChanged("TOUR_ID");
					this.OnTOUR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(50)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(50)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPIRATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXPIRATION_DATE
		{
			get
			{
				return this._EXPIRATION_DATE;
			}
			set
			{
				if ((this._EXPIRATION_DATE != value))
				{
					this.OnEXPIRATION_DATEChanging(value);
					this.SendPropertyChanging();
					this._EXPIRATION_DATE = value;
					this.SendPropertyChanged("EXPIRATION_DATE");
					this.OnEXPIRATION_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(500)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTACHMENT", DbType="NVarChar(MAX)")]
		public string ATTACHMENT
		{
			get
			{
				return this._ATTACHMENT;
			}
			set
			{
				if ((this._ATTACHMENT != value))
				{
					this.OnATTACHMENTChanging(value);
					this.SendPropertyChanging();
					this._ATTACHMENT = value;
					this.SendPropertyChanged("ATTACHMENT");
					this.OnATTACHMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMBEDCODE", DbType="NVarChar(MAX)")]
		public string EMBEDCODE
		{
			get
			{
				return this._EMBEDCODE;
			}
			set
			{
				if ((this._EMBEDCODE != value))
				{
					this.OnEMBEDCODEChanging(value);
					this.SendPropertyChanging();
					this._EMBEDCODE = value;
					this.SendPropertyChanged("EMBEDCODE");
					this.OnEMBEDCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEBURL", DbType="NVarChar(MAX)")]
		public string WEBURL
		{
			get
			{
				return this._WEBURL;
			}
			set
			{
				if ((this._WEBURL != value))
				{
					this.OnWEBURLChanging(value);
					this.SendPropertyChanging();
					this._WEBURL = value;
					this.SendPropertyChanged("WEBURL");
					this.OnWEBURLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOUR_QUOTE_MASTER")]
	public partial class TOUR_QUOTE_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QUOTE_ID;
		
		private int _TOUR_ID;
		
		private string _TOUR_CURRANCY_1;
		
		private System.Nullable<decimal> _ADULT_COST_C1;
		
		private System.Nullable<decimal> _ADULT_TAX_C1;
		
		private System.Nullable<decimal> _ADULT_GST_C1;
		
		private System.Nullable<decimal> _CWB_COST_C1;
		
		private System.Nullable<decimal> _CWB_TAX_C1;
		
		private System.Nullable<decimal> _CWB_GST_C1;
		
		private System.Nullable<decimal> _CNB_COST_C1;
		
		private System.Nullable<decimal> _CNB_TAX_C1;
		
		private System.Nullable<decimal> _CNB_GST_C1;
		
		private System.Nullable<decimal> _INFANT_COST_C1;
		
		private System.Nullable<decimal> _INFANT_TAX_C1;
		
		private System.Nullable<decimal> _INFANT_GST_C1;
		
		private System.Nullable<decimal> _TOTAL_ADULT_COST_C1;
		
		private System.Nullable<decimal> _TOTAL_CWB_COST_C1;
		
		private System.Nullable<decimal> _TOTAL_CNB_COST_C1;
		
		private System.Nullable<decimal> _TOTAL_INFANT_COST_C1;
		
		private string _TOUR_CURRANCY_2;
		
		private System.Nullable<decimal> _ADULT_COST_C2;
		
		private System.Nullable<decimal> _CWB_COST_C2;
		
		private System.Nullable<decimal> _CNB_COST_C2;
		
		private System.Nullable<decimal> _INFANT_COST_C2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQUOTE_IDChanging(int value);
    partial void OnQUOTE_IDChanged();
    partial void OnTOUR_IDChanging(int value);
    partial void OnTOUR_IDChanged();
    partial void OnTOUR_CURRANCY_1Changing(string value);
    partial void OnTOUR_CURRANCY_1Changed();
    partial void OnADULT_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnADULT_COST_C1Changed();
    partial void OnADULT_TAX_C1Changing(System.Nullable<decimal> value);
    partial void OnADULT_TAX_C1Changed();
    partial void OnADULT_GST_C1Changing(System.Nullable<decimal> value);
    partial void OnADULT_GST_C1Changed();
    partial void OnCWB_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnCWB_COST_C1Changed();
    partial void OnCWB_TAX_C1Changing(System.Nullable<decimal> value);
    partial void OnCWB_TAX_C1Changed();
    partial void OnCWB_GST_C1Changing(System.Nullable<decimal> value);
    partial void OnCWB_GST_C1Changed();
    partial void OnCNB_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnCNB_COST_C1Changed();
    partial void OnCNB_TAX_C1Changing(System.Nullable<decimal> value);
    partial void OnCNB_TAX_C1Changed();
    partial void OnCNB_GST_C1Changing(System.Nullable<decimal> value);
    partial void OnCNB_GST_C1Changed();
    partial void OnINFANT_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnINFANT_COST_C1Changed();
    partial void OnINFANT_TAX_C1Changing(System.Nullable<decimal> value);
    partial void OnINFANT_TAX_C1Changed();
    partial void OnINFANT_GST_C1Changing(System.Nullable<decimal> value);
    partial void OnINFANT_GST_C1Changed();
    partial void OnTOTAL_ADULT_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnTOTAL_ADULT_COST_C1Changed();
    partial void OnTOTAL_CWB_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnTOTAL_CWB_COST_C1Changed();
    partial void OnTOTAL_CNB_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnTOTAL_CNB_COST_C1Changed();
    partial void OnTOTAL_INFANT_COST_C1Changing(System.Nullable<decimal> value);
    partial void OnTOTAL_INFANT_COST_C1Changed();
    partial void OnTOUR_CURRANCY_2Changing(string value);
    partial void OnTOUR_CURRANCY_2Changed();
    partial void OnADULT_COST_C2Changing(System.Nullable<decimal> value);
    partial void OnADULT_COST_C2Changed();
    partial void OnCWB_COST_C2Changing(System.Nullable<decimal> value);
    partial void OnCWB_COST_C2Changed();
    partial void OnCNB_COST_C2Changing(System.Nullable<decimal> value);
    partial void OnCNB_COST_C2Changed();
    partial void OnINFANT_COST_C2Changing(System.Nullable<decimal> value);
    partial void OnINFANT_COST_C2Changed();
    #endregion
		
		public TOUR_QUOTE_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOTE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QUOTE_ID
		{
			get
			{
				return this._QUOTE_ID;
			}
			set
			{
				if ((this._QUOTE_ID != value))
				{
					this.OnQUOTE_IDChanging(value);
					this.SendPropertyChanging();
					this._QUOTE_ID = value;
					this.SendPropertyChanged("QUOTE_ID");
					this.OnQUOTE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int NOT NULL")]
		public int TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this.OnTOUR_IDChanging(value);
					this.SendPropertyChanging();
					this._TOUR_ID = value;
					this.SendPropertyChanged("TOUR_ID");
					this.OnTOUR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_CURRANCY_1", DbType="VarChar(50)")]
		public string TOUR_CURRANCY_1
		{
			get
			{
				return this._TOUR_CURRANCY_1;
			}
			set
			{
				if ((this._TOUR_CURRANCY_1 != value))
				{
					this.OnTOUR_CURRANCY_1Changing(value);
					this.SendPropertyChanging();
					this._TOUR_CURRANCY_1 = value;
					this.SendPropertyChanged("TOUR_CURRANCY_1");
					this.OnTOUR_CURRANCY_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADULT_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> ADULT_COST_C1
		{
			get
			{
				return this._ADULT_COST_C1;
			}
			set
			{
				if ((this._ADULT_COST_C1 != value))
				{
					this.OnADULT_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._ADULT_COST_C1 = value;
					this.SendPropertyChanged("ADULT_COST_C1");
					this.OnADULT_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADULT_TAX_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> ADULT_TAX_C1
		{
			get
			{
				return this._ADULT_TAX_C1;
			}
			set
			{
				if ((this._ADULT_TAX_C1 != value))
				{
					this.OnADULT_TAX_C1Changing(value);
					this.SendPropertyChanging();
					this._ADULT_TAX_C1 = value;
					this.SendPropertyChanged("ADULT_TAX_C1");
					this.OnADULT_TAX_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADULT_GST_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> ADULT_GST_C1
		{
			get
			{
				return this._ADULT_GST_C1;
			}
			set
			{
				if ((this._ADULT_GST_C1 != value))
				{
					this.OnADULT_GST_C1Changing(value);
					this.SendPropertyChanging();
					this._ADULT_GST_C1 = value;
					this.SendPropertyChanged("ADULT_GST_C1");
					this.OnADULT_GST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CWB_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> CWB_COST_C1
		{
			get
			{
				return this._CWB_COST_C1;
			}
			set
			{
				if ((this._CWB_COST_C1 != value))
				{
					this.OnCWB_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._CWB_COST_C1 = value;
					this.SendPropertyChanged("CWB_COST_C1");
					this.OnCWB_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CWB_TAX_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> CWB_TAX_C1
		{
			get
			{
				return this._CWB_TAX_C1;
			}
			set
			{
				if ((this._CWB_TAX_C1 != value))
				{
					this.OnCWB_TAX_C1Changing(value);
					this.SendPropertyChanging();
					this._CWB_TAX_C1 = value;
					this.SendPropertyChanged("CWB_TAX_C1");
					this.OnCWB_TAX_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CWB_GST_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> CWB_GST_C1
		{
			get
			{
				return this._CWB_GST_C1;
			}
			set
			{
				if ((this._CWB_GST_C1 != value))
				{
					this.OnCWB_GST_C1Changing(value);
					this.SendPropertyChanging();
					this._CWB_GST_C1 = value;
					this.SendPropertyChanged("CWB_GST_C1");
					this.OnCWB_GST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNB_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> CNB_COST_C1
		{
			get
			{
				return this._CNB_COST_C1;
			}
			set
			{
				if ((this._CNB_COST_C1 != value))
				{
					this.OnCNB_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._CNB_COST_C1 = value;
					this.SendPropertyChanged("CNB_COST_C1");
					this.OnCNB_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNB_TAX_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> CNB_TAX_C1
		{
			get
			{
				return this._CNB_TAX_C1;
			}
			set
			{
				if ((this._CNB_TAX_C1 != value))
				{
					this.OnCNB_TAX_C1Changing(value);
					this.SendPropertyChanging();
					this._CNB_TAX_C1 = value;
					this.SendPropertyChanged("CNB_TAX_C1");
					this.OnCNB_TAX_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNB_GST_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> CNB_GST_C1
		{
			get
			{
				return this._CNB_GST_C1;
			}
			set
			{
				if ((this._CNB_GST_C1 != value))
				{
					this.OnCNB_GST_C1Changing(value);
					this.SendPropertyChanging();
					this._CNB_GST_C1 = value;
					this.SendPropertyChanged("CNB_GST_C1");
					this.OnCNB_GST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFANT_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> INFANT_COST_C1
		{
			get
			{
				return this._INFANT_COST_C1;
			}
			set
			{
				if ((this._INFANT_COST_C1 != value))
				{
					this.OnINFANT_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._INFANT_COST_C1 = value;
					this.SendPropertyChanged("INFANT_COST_C1");
					this.OnINFANT_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFANT_TAX_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> INFANT_TAX_C1
		{
			get
			{
				return this._INFANT_TAX_C1;
			}
			set
			{
				if ((this._INFANT_TAX_C1 != value))
				{
					this.OnINFANT_TAX_C1Changing(value);
					this.SendPropertyChanging();
					this._INFANT_TAX_C1 = value;
					this.SendPropertyChanged("INFANT_TAX_C1");
					this.OnINFANT_TAX_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFANT_GST_C1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> INFANT_GST_C1
		{
			get
			{
				return this._INFANT_GST_C1;
			}
			set
			{
				if ((this._INFANT_GST_C1 != value))
				{
					this.OnINFANT_GST_C1Changing(value);
					this.SendPropertyChanging();
					this._INFANT_GST_C1 = value;
					this.SendPropertyChanged("INFANT_GST_C1");
					this.OnINFANT_GST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_ADULT_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TOTAL_ADULT_COST_C1
		{
			get
			{
				return this._TOTAL_ADULT_COST_C1;
			}
			set
			{
				if ((this._TOTAL_ADULT_COST_C1 != value))
				{
					this.OnTOTAL_ADULT_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._TOTAL_ADULT_COST_C1 = value;
					this.SendPropertyChanged("TOTAL_ADULT_COST_C1");
					this.OnTOTAL_ADULT_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CWB_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TOTAL_CWB_COST_C1
		{
			get
			{
				return this._TOTAL_CWB_COST_C1;
			}
			set
			{
				if ((this._TOTAL_CWB_COST_C1 != value))
				{
					this.OnTOTAL_CWB_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._TOTAL_CWB_COST_C1 = value;
					this.SendPropertyChanged("TOTAL_CWB_COST_C1");
					this.OnTOTAL_CWB_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CNB_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TOTAL_CNB_COST_C1
		{
			get
			{
				return this._TOTAL_CNB_COST_C1;
			}
			set
			{
				if ((this._TOTAL_CNB_COST_C1 != value))
				{
					this.OnTOTAL_CNB_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._TOTAL_CNB_COST_C1 = value;
					this.SendPropertyChanged("TOTAL_CNB_COST_C1");
					this.OnTOTAL_CNB_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_INFANT_COST_C1", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TOTAL_INFANT_COST_C1
		{
			get
			{
				return this._TOTAL_INFANT_COST_C1;
			}
			set
			{
				if ((this._TOTAL_INFANT_COST_C1 != value))
				{
					this.OnTOTAL_INFANT_COST_C1Changing(value);
					this.SendPropertyChanging();
					this._TOTAL_INFANT_COST_C1 = value;
					this.SendPropertyChanged("TOTAL_INFANT_COST_C1");
					this.OnTOTAL_INFANT_COST_C1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_CURRANCY_2", DbType="VarChar(50)")]
		public string TOUR_CURRANCY_2
		{
			get
			{
				return this._TOUR_CURRANCY_2;
			}
			set
			{
				if ((this._TOUR_CURRANCY_2 != value))
				{
					this.OnTOUR_CURRANCY_2Changing(value);
					this.SendPropertyChanging();
					this._TOUR_CURRANCY_2 = value;
					this.SendPropertyChanged("TOUR_CURRANCY_2");
					this.OnTOUR_CURRANCY_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADULT_COST_C2", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> ADULT_COST_C2
		{
			get
			{
				return this._ADULT_COST_C2;
			}
			set
			{
				if ((this._ADULT_COST_C2 != value))
				{
					this.OnADULT_COST_C2Changing(value);
					this.SendPropertyChanging();
					this._ADULT_COST_C2 = value;
					this.SendPropertyChanged("ADULT_COST_C2");
					this.OnADULT_COST_C2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CWB_COST_C2", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> CWB_COST_C2
		{
			get
			{
				return this._CWB_COST_C2;
			}
			set
			{
				if ((this._CWB_COST_C2 != value))
				{
					this.OnCWB_COST_C2Changing(value);
					this.SendPropertyChanging();
					this._CWB_COST_C2 = value;
					this.SendPropertyChanged("CWB_COST_C2");
					this.OnCWB_COST_C2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNB_COST_C2", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> CNB_COST_C2
		{
			get
			{
				return this._CNB_COST_C2;
			}
			set
			{
				if ((this._CNB_COST_C2 != value))
				{
					this.OnCNB_COST_C2Changing(value);
					this.SendPropertyChanging();
					this._CNB_COST_C2 = value;
					this.SendPropertyChanged("CNB_COST_C2");
					this.OnCNB_COST_C2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFANT_COST_C2", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> INFANT_COST_C2
		{
			get
			{
				return this._INFANT_COST_C2;
			}
			set
			{
				if ((this._INFANT_COST_C2 != value))
				{
					this.OnINFANT_COST_C2Changing(value);
					this.SendPropertyChanging();
					this._INFANT_COST_C2 = value;
					this.SendPropertyChanged("INFANT_COST_C2");
					this.OnINFANT_COST_C2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_TOUR_TRANSPORTATION_DETAILS")]
	public partial class VIEW_TOUR_TRANSPORTATION_DETAIL
	{
		
		private int _TOUR_ID;
		
		private string _TRANSPORT_MODE;
		
		private string _TRANSPORT_NO;
		
		private string _TRANSPORT_DETAILS;
		
		private string _DATE_OF_ARRIVAL;
		
		private System.Nullable<System.DateTime> _TIME_OF_ARRIVAL;
		
		private System.Nullable<int> _PLACE_OF_ARRIVAL;
		
		private string _DATE_OF_DEPARTURE;
		
		private System.Nullable<System.DateTime> _TIME_OF_DEPARTURE;
		
		private System.Nullable<int> _PLACE_OF_DEPARTURE;
		
		private System.Nullable<int> _NO_OF_SEATS;
		
		private System.Nullable<decimal> _AMOUNT;
		
		private string _BOOKING_REQUEST_TO;
		
		private int _SR_NO;
		
		public VIEW_TOUR_TRANSPORTATION_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int NOT NULL")]
		public int TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSPORT_MODE", DbType="VarChar(50)")]
		public string TRANSPORT_MODE
		{
			get
			{
				return this._TRANSPORT_MODE;
			}
			set
			{
				if ((this._TRANSPORT_MODE != value))
				{
					this._TRANSPORT_MODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSPORT_NO", DbType="VarChar(50)")]
		public string TRANSPORT_NO
		{
			get
			{
				return this._TRANSPORT_NO;
			}
			set
			{
				if ((this._TRANSPORT_NO != value))
				{
					this._TRANSPORT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSPORT_DETAILS", DbType="NVarChar(255)")]
		public string TRANSPORT_DETAILS
		{
			get
			{
				return this._TRANSPORT_DETAILS;
			}
			set
			{
				if ((this._TRANSPORT_DETAILS != value))
				{
					this._TRANSPORT_DETAILS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_OF_ARRIVAL", DbType="VarChar(10)")]
		public string DATE_OF_ARRIVAL
		{
			get
			{
				return this._DATE_OF_ARRIVAL;
			}
			set
			{
				if ((this._DATE_OF_ARRIVAL != value))
				{
					this._DATE_OF_ARRIVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_OF_ARRIVAL", DbType="DateTime")]
		public System.Nullable<System.DateTime> TIME_OF_ARRIVAL
		{
			get
			{
				return this._TIME_OF_ARRIVAL;
			}
			set
			{
				if ((this._TIME_OF_ARRIVAL != value))
				{
					this._TIME_OF_ARRIVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLACE_OF_ARRIVAL", DbType="Int")]
		public System.Nullable<int> PLACE_OF_ARRIVAL
		{
			get
			{
				return this._PLACE_OF_ARRIVAL;
			}
			set
			{
				if ((this._PLACE_OF_ARRIVAL != value))
				{
					this._PLACE_OF_ARRIVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_OF_DEPARTURE", DbType="VarChar(10)")]
		public string DATE_OF_DEPARTURE
		{
			get
			{
				return this._DATE_OF_DEPARTURE;
			}
			set
			{
				if ((this._DATE_OF_DEPARTURE != value))
				{
					this._DATE_OF_DEPARTURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_OF_DEPARTURE", DbType="DateTime")]
		public System.Nullable<System.DateTime> TIME_OF_DEPARTURE
		{
			get
			{
				return this._TIME_OF_DEPARTURE;
			}
			set
			{
				if ((this._TIME_OF_DEPARTURE != value))
				{
					this._TIME_OF_DEPARTURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLACE_OF_DEPARTURE", DbType="Int")]
		public System.Nullable<int> PLACE_OF_DEPARTURE
		{
			get
			{
				return this._PLACE_OF_DEPARTURE;
			}
			set
			{
				if ((this._PLACE_OF_DEPARTURE != value))
				{
					this._PLACE_OF_DEPARTURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_SEATS", DbType="Int")]
		public System.Nullable<int> NO_OF_SEATS
		{
			get
			{
				return this._NO_OF_SEATS;
			}
			set
			{
				if ((this._NO_OF_SEATS != value))
				{
					this._NO_OF_SEATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				if ((this._AMOUNT != value))
				{
					this._AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_REQUEST_TO", DbType="VarChar(50)")]
		public string BOOKING_REQUEST_TO
		{
			get
			{
				return this._BOOKING_REQUEST_TO;
			}
			set
			{
				if ((this._BOOKING_REQUEST_TO != value))
				{
					this._BOOKING_REQUEST_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SR_NO", DbType="Int NOT NULL")]
		public int SR_NO
		{
			get
			{
				return this._SR_NO;
			}
			set
			{
				if ((this._SR_NO != value))
				{
					this._SR_NO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_DECK_CABINE_DETAIL")]
	public partial class VIEW_DECK_CABINE_DETAIL
	{
		
		private System.Nullable<int> _CABINES;
		
		private System.Nullable<int> _TOUR_ID;
		
		private System.Nullable<int> _DECK_NO;
		
		private System.Nullable<int> _TOUR_CRUISE_ID;
		
		public VIEW_DECK_CABINE_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CABINES", DbType="Int")]
		public System.Nullable<int> CABINES
		{
			get
			{
				return this._CABINES;
			}
			set
			{
				if ((this._CABINES != value))
				{
					this._CABINES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int")]
		public System.Nullable<int> TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DECK_NO", DbType="Int")]
		public System.Nullable<int> DECK_NO
		{
			get
			{
				return this._DECK_NO;
			}
			set
			{
				if ((this._DECK_NO != value))
				{
					this._DECK_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_CRUISE_ID", DbType="Int")]
		public System.Nullable<int> TOUR_CRUISE_ID
		{
			get
			{
				return this._TOUR_CRUISE_ID;
			}
			set
			{
				if ((this._TOUR_CRUISE_ID != value))
				{
					this._TOUR_CRUISE_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_COUNTRY_FOR_VISA")]
	public partial class VIEW_COUNTRY_FOR_VISA
	{
		
		private int _SR_NO;
		
		private System.Nullable<int> _TOUR_ID;
		
		private string _COUNTRY_NAME;
		
		private System.Nullable<int> _TOUR_CRUISE_ID;
		
		public VIEW_COUNTRY_FOR_VISA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SR_NO", DbType="Int NOT NULL")]
		public int SR_NO
		{
			get
			{
				return this._SR_NO;
			}
			set
			{
				if ((this._SR_NO != value))
				{
					this._SR_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int")]
		public System.Nullable<int> TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_NAME", DbType="VarChar(50)")]
		public string COUNTRY_NAME
		{
			get
			{
				return this._COUNTRY_NAME;
			}
			set
			{
				if ((this._COUNTRY_NAME != value))
				{
					this._COUNTRY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_CRUISE_ID", DbType="Int")]
		public System.Nullable<int> TOUR_CRUISE_ID
		{
			get
			{
				return this._TOUR_CRUISE_ID;
			}
			set
			{
				if ((this._TOUR_CRUISE_ID != value))
				{
					this._TOUR_CRUISE_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_TOUR_MASTER")]
	public partial class VIEW_TOUR_MASTER
	{
		
		private string _TOUR_CODE;
		
		private string _TOUR_SHORT_NAME;
		
		private string _TOUR_LONG_DESC;
		
		private string _TOUR_TYPE_NAME;
		
		private string _TOUR_SUB_TYPE_NAME;
		
		private string _TOUR_ITENARY_TYPE_NAME;
		
		private string _BASE_TOUR;
		
		private string _TOUR_FROM_DATE;
		
		private string _TOUR_TO_DATE;
		
		private System.Nullable<int> _NO_OF_DAYS;
		
		private System.Nullable<int> _NO_OF_NIGHTS;
		
		private int _NO_OF_SEATS;
		
		private string _COUNTRIES_FOR_VISA_TEXT;
		
		private string _CITY_TO_TRAVEL;
		
		private string _START_END_CITY_TEXT;
		
		private System.Nullable<int> _GUIDE_TITLE;
		
		private int _TOUR_ID;
		
		private System.Nullable<int> _NO_OF_AVAILABLE_SEATS;
		
		public VIEW_TOUR_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_CODE", DbType="VarChar(50)")]
		public string TOUR_CODE
		{
			get
			{
				return this._TOUR_CODE;
			}
			set
			{
				if ((this._TOUR_CODE != value))
				{
					this._TOUR_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_SHORT_NAME", DbType="VarChar(50)")]
		public string TOUR_SHORT_NAME
		{
			get
			{
				return this._TOUR_SHORT_NAME;
			}
			set
			{
				if ((this._TOUR_SHORT_NAME != value))
				{
					this._TOUR_SHORT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_LONG_DESC", DbType="VarChar(255)")]
		public string TOUR_LONG_DESC
		{
			get
			{
				return this._TOUR_LONG_DESC;
			}
			set
			{
				if ((this._TOUR_LONG_DESC != value))
				{
					this._TOUR_LONG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_TYPE_NAME", DbType="VarChar(50)")]
		public string TOUR_TYPE_NAME
		{
			get
			{
				return this._TOUR_TYPE_NAME;
			}
			set
			{
				if ((this._TOUR_TYPE_NAME != value))
				{
					this._TOUR_TYPE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_SUB_TYPE_NAME", DbType="VarChar(50)")]
		public string TOUR_SUB_TYPE_NAME
		{
			get
			{
				return this._TOUR_SUB_TYPE_NAME;
			}
			set
			{
				if ((this._TOUR_SUB_TYPE_NAME != value))
				{
					this._TOUR_SUB_TYPE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ITENARY_TYPE_NAME", DbType="VarChar(50)")]
		public string TOUR_ITENARY_TYPE_NAME
		{
			get
			{
				return this._TOUR_ITENARY_TYPE_NAME;
			}
			set
			{
				if ((this._TOUR_ITENARY_TYPE_NAME != value))
				{
					this._TOUR_ITENARY_TYPE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASE_TOUR", DbType="VarChar(500)")]
		public string BASE_TOUR
		{
			get
			{
				return this._BASE_TOUR;
			}
			set
			{
				if ((this._BASE_TOUR != value))
				{
					this._BASE_TOUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_FROM_DATE", DbType="VarChar(10)")]
		public string TOUR_FROM_DATE
		{
			get
			{
				return this._TOUR_FROM_DATE;
			}
			set
			{
				if ((this._TOUR_FROM_DATE != value))
				{
					this._TOUR_FROM_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_TO_DATE", DbType="VarChar(10)")]
		public string TOUR_TO_DATE
		{
			get
			{
				return this._TOUR_TO_DATE;
			}
			set
			{
				if ((this._TOUR_TO_DATE != value))
				{
					this._TOUR_TO_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_DAYS", DbType="Int")]
		public System.Nullable<int> NO_OF_DAYS
		{
			get
			{
				return this._NO_OF_DAYS;
			}
			set
			{
				if ((this._NO_OF_DAYS != value))
				{
					this._NO_OF_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_NIGHTS", DbType="Int")]
		public System.Nullable<int> NO_OF_NIGHTS
		{
			get
			{
				return this._NO_OF_NIGHTS;
			}
			set
			{
				if ((this._NO_OF_NIGHTS != value))
				{
					this._NO_OF_NIGHTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_SEATS", DbType="Int NOT NULL")]
		public int NO_OF_SEATS
		{
			get
			{
				return this._NO_OF_SEATS;
			}
			set
			{
				if ((this._NO_OF_SEATS != value))
				{
					this._NO_OF_SEATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRIES_FOR_VISA_TEXT", DbType="VarChar(MAX)")]
		public string COUNTRIES_FOR_VISA_TEXT
		{
			get
			{
				return this._COUNTRIES_FOR_VISA_TEXT;
			}
			set
			{
				if ((this._COUNTRIES_FOR_VISA_TEXT != value))
				{
					this._COUNTRIES_FOR_VISA_TEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_TO_TRAVEL", DbType="VarChar(50)")]
		public string CITY_TO_TRAVEL
		{
			get
			{
				return this._CITY_TO_TRAVEL;
			}
			set
			{
				if ((this._CITY_TO_TRAVEL != value))
				{
					this._CITY_TO_TRAVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_END_CITY_TEXT", DbType="VarChar(MAX)")]
		public string START_END_CITY_TEXT
		{
			get
			{
				return this._START_END_CITY_TEXT;
			}
			set
			{
				if ((this._START_END_CITY_TEXT != value))
				{
					this._START_END_CITY_TEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUIDE_TITLE", DbType="Int")]
		public System.Nullable<int> GUIDE_TITLE
		{
			get
			{
				return this._GUIDE_TITLE;
			}
			set
			{
				if ((this._GUIDE_TITLE != value))
				{
					this._GUIDE_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int NOT NULL")]
		public int TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_AVAILABLE_SEATS", DbType="Int")]
		public System.Nullable<int> NO_OF_AVAILABLE_SEATS
		{
			get
			{
				return this._NO_OF_AVAILABLE_SEATS;
			}
			set
			{
				if ((this._NO_OF_AVAILABLE_SEATS != value))
				{
					this._NO_OF_AVAILABLE_SEATS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_CRUISE_DETAIL")]
	public partial class VIEW_CRUISE_DETAIL
	{
		
		private string _BOOKING_REQ_TO;
		
		private string _CHECK_REQ_TO;
		
		private string _APPROVED_BY;
		
		private string _BOOKED_BY;
		
		private int _CRUISE_SR_NO;
		
		private string _DATE_OF_SAILING;
		
		private string _DATE_OF_ARRIVAL;
		
		private System.Nullable<int> _CABINE_TO_BE_BLOCKED;
		
		private string _CHECK_REQ_DATE;
		
		private string _CHECK_COMMENTS;
		
		private System.Nullable<int> _TOTAL_ROOMS_BLOCKED;
		
		private string _TIME_LIMIT;
		
		private string _BOOKING_REQ_DATE;
		
		private System.Nullable<decimal> _TOTAL_AMOUNT;
		
		private System.Nullable<decimal> _TAX;
		
		private System.Nullable<decimal> _GST;
		
		private System.Nullable<int> _TOTAL_CABINES_ALLOTED;
		
		private System.Nullable<int> _PARTIAL_CABINES_ALLOTED;
		
		private System.Nullable<int> _ASTOTAL_ADULTS_ALLOTED;
		
		private System.Nullable<int> _TOTAL_CWB_ALLOTED;
		
		private System.Nullable<int> _TOTAL_CNB_ALLOTED;
		
		private System.Nullable<int> _TOTAL_INFANT_ALLOTED;
		
		private System.Nullable<int> _AVAILABLE_CABINES;
		
		private string _CRUISE_NAME;
		
		private string _TIME_OF_DEPARTURE;
		
		private string _TIME_OF_ARRIVAL;
		
		private string _CRUISE_COMP_NAME;
		
		private string _CABINE_CATEGORY;
		
		private string _BOOKING_STATUS_NAME;
		
		private System.Nullable<int> _TOUR_ID;
		
		public VIEW_CRUISE_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_REQ_TO", DbType="VarChar(101)")]
		public string BOOKING_REQ_TO
		{
			get
			{
				return this._BOOKING_REQ_TO;
			}
			set
			{
				if ((this._BOOKING_REQ_TO != value))
				{
					this._BOOKING_REQ_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_REQ_TO", DbType="VarChar(101)")]
		public string CHECK_REQ_TO
		{
			get
			{
				return this._CHECK_REQ_TO;
			}
			set
			{
				if ((this._CHECK_REQ_TO != value))
				{
					this._CHECK_REQ_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVED_BY", DbType="VarChar(50)")]
		public string APPROVED_BY
		{
			get
			{
				return this._APPROVED_BY;
			}
			set
			{
				if ((this._APPROVED_BY != value))
				{
					this._APPROVED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKED_BY", DbType="VarChar(50)")]
		public string BOOKED_BY
		{
			get
			{
				return this._BOOKED_BY;
			}
			set
			{
				if ((this._BOOKED_BY != value))
				{
					this._BOOKED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRUISE_SR_NO", DbType="Int NOT NULL")]
		public int CRUISE_SR_NO
		{
			get
			{
				return this._CRUISE_SR_NO;
			}
			set
			{
				if ((this._CRUISE_SR_NO != value))
				{
					this._CRUISE_SR_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_OF_SAILING", DbType="VarChar(10)")]
		public string DATE_OF_SAILING
		{
			get
			{
				return this._DATE_OF_SAILING;
			}
			set
			{
				if ((this._DATE_OF_SAILING != value))
				{
					this._DATE_OF_SAILING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_OF_ARRIVAL", DbType="VarChar(10)")]
		public string DATE_OF_ARRIVAL
		{
			get
			{
				return this._DATE_OF_ARRIVAL;
			}
			set
			{
				if ((this._DATE_OF_ARRIVAL != value))
				{
					this._DATE_OF_ARRIVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CABINE_TO_BE_BLOCKED", DbType="Int")]
		public System.Nullable<int> CABINE_TO_BE_BLOCKED
		{
			get
			{
				return this._CABINE_TO_BE_BLOCKED;
			}
			set
			{
				if ((this._CABINE_TO_BE_BLOCKED != value))
				{
					this._CABINE_TO_BE_BLOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_REQ_DATE", DbType="VarChar(10)")]
		public string CHECK_REQ_DATE
		{
			get
			{
				return this._CHECK_REQ_DATE;
			}
			set
			{
				if ((this._CHECK_REQ_DATE != value))
				{
					this._CHECK_REQ_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_COMMENTS", DbType="VarChar(500)")]
		public string CHECK_COMMENTS
		{
			get
			{
				return this._CHECK_COMMENTS;
			}
			set
			{
				if ((this._CHECK_COMMENTS != value))
				{
					this._CHECK_COMMENTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_ROOMS_BLOCKED", DbType="Int")]
		public System.Nullable<int> TOTAL_ROOMS_BLOCKED
		{
			get
			{
				return this._TOTAL_ROOMS_BLOCKED;
			}
			set
			{
				if ((this._TOTAL_ROOMS_BLOCKED != value))
				{
					this._TOTAL_ROOMS_BLOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_LIMIT", DbType="VarChar(10)")]
		public string TIME_LIMIT
		{
			get
			{
				return this._TIME_LIMIT;
			}
			set
			{
				if ((this._TIME_LIMIT != value))
				{
					this._TIME_LIMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_REQ_DATE", DbType="VarChar(10)")]
		public string BOOKING_REQ_DATE
		{
			get
			{
				return this._BOOKING_REQ_DATE;
			}
			set
			{
				if ((this._BOOKING_REQ_DATE != value))
				{
					this._BOOKING_REQ_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNT", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TOTAL_AMOUNT
		{
			get
			{
				return this._TOTAL_AMOUNT;
			}
			set
			{
				if ((this._TOTAL_AMOUNT != value))
				{
					this._TOTAL_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TAX
		{
			get
			{
				return this._TAX;
			}
			set
			{
				if ((this._TAX != value))
				{
					this._TAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GST", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> GST
		{
			get
			{
				return this._GST;
			}
			set
			{
				if ((this._GST != value))
				{
					this._GST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CABINES_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_CABINES_ALLOTED
		{
			get
			{
				return this._TOTAL_CABINES_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_CABINES_ALLOTED != value))
				{
					this._TOTAL_CABINES_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTIAL_CABINES_ALLOTED", DbType="Int")]
		public System.Nullable<int> PARTIAL_CABINES_ALLOTED
		{
			get
			{
				return this._PARTIAL_CABINES_ALLOTED;
			}
			set
			{
				if ((this._PARTIAL_CABINES_ALLOTED != value))
				{
					this._PARTIAL_CABINES_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASTOTAL_ADULTS_ALLOTED", DbType="Int")]
		public System.Nullable<int> ASTOTAL_ADULTS_ALLOTED
		{
			get
			{
				return this._ASTOTAL_ADULTS_ALLOTED;
			}
			set
			{
				if ((this._ASTOTAL_ADULTS_ALLOTED != value))
				{
					this._ASTOTAL_ADULTS_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CWB_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_CWB_ALLOTED
		{
			get
			{
				return this._TOTAL_CWB_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_CWB_ALLOTED != value))
				{
					this._TOTAL_CWB_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CNB_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_CNB_ALLOTED
		{
			get
			{
				return this._TOTAL_CNB_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_CNB_ALLOTED != value))
				{
					this._TOTAL_CNB_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_INFANT_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_INFANT_ALLOTED
		{
			get
			{
				return this._TOTAL_INFANT_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_INFANT_ALLOTED != value))
				{
					this._TOTAL_INFANT_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVAILABLE_CABINES", DbType="Int")]
		public System.Nullable<int> AVAILABLE_CABINES
		{
			get
			{
				return this._AVAILABLE_CABINES;
			}
			set
			{
				if ((this._AVAILABLE_CABINES != value))
				{
					this._AVAILABLE_CABINES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRUISE_NAME", DbType="VarChar(50)")]
		public string CRUISE_NAME
		{
			get
			{
				return this._CRUISE_NAME;
			}
			set
			{
				if ((this._CRUISE_NAME != value))
				{
					this._CRUISE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_OF_DEPARTURE", DbType="VarChar(10)")]
		public string TIME_OF_DEPARTURE
		{
			get
			{
				return this._TIME_OF_DEPARTURE;
			}
			set
			{
				if ((this._TIME_OF_DEPARTURE != value))
				{
					this._TIME_OF_DEPARTURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_OF_ARRIVAL", DbType="VarChar(10)")]
		public string TIME_OF_ARRIVAL
		{
			get
			{
				return this._TIME_OF_ARRIVAL;
			}
			set
			{
				if ((this._TIME_OF_ARRIVAL != value))
				{
					this._TIME_OF_ARRIVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRUISE_COMP_NAME", DbType="VarChar(50)")]
		public string CRUISE_COMP_NAME
		{
			get
			{
				return this._CRUISE_COMP_NAME;
			}
			set
			{
				if ((this._CRUISE_COMP_NAME != value))
				{
					this._CRUISE_COMP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CABINE_CATEGORY", DbType="VarChar(100)")]
		public string CABINE_CATEGORY
		{
			get
			{
				return this._CABINE_CATEGORY;
			}
			set
			{
				if ((this._CABINE_CATEGORY != value))
				{
					this._CABINE_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_STATUS_NAME", DbType="VarChar(100)")]
		public string BOOKING_STATUS_NAME
		{
			get
			{
				return this._BOOKING_STATUS_NAME;
			}
			set
			{
				if ((this._BOOKING_STATUS_NAME != value))
				{
					this._BOOKING_STATUS_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int")]
		public System.Nullable<int> TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_FLIGHT_DETAIL")]
	public partial class VIEW_FLIGHT_DETAIL
	{
		
		private string _BOOKING_REQ_TO;
		
		private string _CHECK_REQ_TO;
		
		private string _APPROVED_BY;
		
		private string _BOOKED_BY;
		
		private int _FLIGHT_SR_NO;
		
		private System.Nullable<int> _TOUR_ID;
		
		private string _DATE_OF_DEPARTURE;
		
		private string _DATE_OF_ARRIVAL;
		
		private System.Nullable<int> _SEATS_TO_BE_BLOCKED;
		
		private string _CHECK_REQ_DATE;
		
		private string _CHECK_COMMENTS;
		
		private System.Nullable<int> _SEATS_TO_BLOCK;
		
		private string _TIME_LIMIT;
		
		private string _BOOKING_REQ_DATE;
		
		private System.Nullable<decimal> _TOTAL_AMOUNT;
		
		private System.Nullable<decimal> _TAX;
		
		private System.Nullable<decimal> _GST;
		
		private System.Nullable<int> _TOTAL_SEATS_ALLOTED;
		
		private System.Nullable<int> _TOTAL_ADULTS_ALLOTED;
		
		private System.Nullable<int> _TOTAL_CHILD_ALLOTED;
		
		private System.Nullable<int> _TOTAL_INFANT_ALLOTED;
		
		private System.Nullable<int> _AVAILABLE_SEATS;
		
		private System.Nullable<int> _FLIGHT_ID;
		
		private string _FLIGHT_NO;
		
		private string _DEP_TIME;
		
		private string _ARRIVAL_TIME;
		
		private string _AIRLINE_NAME;
		
		private string _CLASS_NAME;
		
		private string _BOOKING_STATUS_NAME;
		
		public VIEW_FLIGHT_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_REQ_TO", DbType="VarChar(101)")]
		public string BOOKING_REQ_TO
		{
			get
			{
				return this._BOOKING_REQ_TO;
			}
			set
			{
				if ((this._BOOKING_REQ_TO != value))
				{
					this._BOOKING_REQ_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_REQ_TO", DbType="VarChar(101)")]
		public string CHECK_REQ_TO
		{
			get
			{
				return this._CHECK_REQ_TO;
			}
			set
			{
				if ((this._CHECK_REQ_TO != value))
				{
					this._CHECK_REQ_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVED_BY", DbType="VarChar(50)")]
		public string APPROVED_BY
		{
			get
			{
				return this._APPROVED_BY;
			}
			set
			{
				if ((this._APPROVED_BY != value))
				{
					this._APPROVED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKED_BY", DbType="VarChar(50)")]
		public string BOOKED_BY
		{
			get
			{
				return this._BOOKED_BY;
			}
			set
			{
				if ((this._BOOKED_BY != value))
				{
					this._BOOKED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLIGHT_SR_NO", DbType="Int NOT NULL")]
		public int FLIGHT_SR_NO
		{
			get
			{
				return this._FLIGHT_SR_NO;
			}
			set
			{
				if ((this._FLIGHT_SR_NO != value))
				{
					this._FLIGHT_SR_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int")]
		public System.Nullable<int> TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_OF_DEPARTURE", DbType="VarChar(10)")]
		public string DATE_OF_DEPARTURE
		{
			get
			{
				return this._DATE_OF_DEPARTURE;
			}
			set
			{
				if ((this._DATE_OF_DEPARTURE != value))
				{
					this._DATE_OF_DEPARTURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_OF_ARRIVAL", DbType="VarChar(10)")]
		public string DATE_OF_ARRIVAL
		{
			get
			{
				return this._DATE_OF_ARRIVAL;
			}
			set
			{
				if ((this._DATE_OF_ARRIVAL != value))
				{
					this._DATE_OF_ARRIVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEATS_TO_BE_BLOCKED", DbType="Int")]
		public System.Nullable<int> SEATS_TO_BE_BLOCKED
		{
			get
			{
				return this._SEATS_TO_BE_BLOCKED;
			}
			set
			{
				if ((this._SEATS_TO_BE_BLOCKED != value))
				{
					this._SEATS_TO_BE_BLOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_REQ_DATE", DbType="VarChar(10)")]
		public string CHECK_REQ_DATE
		{
			get
			{
				return this._CHECK_REQ_DATE;
			}
			set
			{
				if ((this._CHECK_REQ_DATE != value))
				{
					this._CHECK_REQ_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_COMMENTS", DbType="VarChar(500)")]
		public string CHECK_COMMENTS
		{
			get
			{
				return this._CHECK_COMMENTS;
			}
			set
			{
				if ((this._CHECK_COMMENTS != value))
				{
					this._CHECK_COMMENTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEATS_TO_BLOCK", DbType="Int")]
		public System.Nullable<int> SEATS_TO_BLOCK
		{
			get
			{
				return this._SEATS_TO_BLOCK;
			}
			set
			{
				if ((this._SEATS_TO_BLOCK != value))
				{
					this._SEATS_TO_BLOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_LIMIT", DbType="VarChar(10)")]
		public string TIME_LIMIT
		{
			get
			{
				return this._TIME_LIMIT;
			}
			set
			{
				if ((this._TIME_LIMIT != value))
				{
					this._TIME_LIMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_REQ_DATE", DbType="VarChar(10)")]
		public string BOOKING_REQ_DATE
		{
			get
			{
				return this._BOOKING_REQ_DATE;
			}
			set
			{
				if ((this._BOOKING_REQ_DATE != value))
				{
					this._BOOKING_REQ_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNT", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TOTAL_AMOUNT
		{
			get
			{
				return this._TOTAL_AMOUNT;
			}
			set
			{
				if ((this._TOTAL_AMOUNT != value))
				{
					this._TOTAL_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TAX
		{
			get
			{
				return this._TAX;
			}
			set
			{
				if ((this._TAX != value))
				{
					this._TAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GST", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> GST
		{
			get
			{
				return this._GST;
			}
			set
			{
				if ((this._GST != value))
				{
					this._GST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_SEATS_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_SEATS_ALLOTED
		{
			get
			{
				return this._TOTAL_SEATS_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_SEATS_ALLOTED != value))
				{
					this._TOTAL_SEATS_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_ADULTS_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_ADULTS_ALLOTED
		{
			get
			{
				return this._TOTAL_ADULTS_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_ADULTS_ALLOTED != value))
				{
					this._TOTAL_ADULTS_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CHILD_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_CHILD_ALLOTED
		{
			get
			{
				return this._TOTAL_CHILD_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_CHILD_ALLOTED != value))
				{
					this._TOTAL_CHILD_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_INFANT_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_INFANT_ALLOTED
		{
			get
			{
				return this._TOTAL_INFANT_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_INFANT_ALLOTED != value))
				{
					this._TOTAL_INFANT_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVAILABLE_SEATS", DbType="Int")]
		public System.Nullable<int> AVAILABLE_SEATS
		{
			get
			{
				return this._AVAILABLE_SEATS;
			}
			set
			{
				if ((this._AVAILABLE_SEATS != value))
				{
					this._AVAILABLE_SEATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLIGHT_ID", DbType="Int")]
		public System.Nullable<int> FLIGHT_ID
		{
			get
			{
				return this._FLIGHT_ID;
			}
			set
			{
				if ((this._FLIGHT_ID != value))
				{
					this._FLIGHT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLIGHT_NO", DbType="VarChar(50)")]
		public string FLIGHT_NO
		{
			get
			{
				return this._FLIGHT_NO;
			}
			set
			{
				if ((this._FLIGHT_NO != value))
				{
					this._FLIGHT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEP_TIME", DbType="VarChar(50)")]
		public string DEP_TIME
		{
			get
			{
				return this._DEP_TIME;
			}
			set
			{
				if ((this._DEP_TIME != value))
				{
					this._DEP_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARRIVAL_TIME", DbType="VarChar(50)")]
		public string ARRIVAL_TIME
		{
			get
			{
				return this._ARRIVAL_TIME;
			}
			set
			{
				if ((this._ARRIVAL_TIME != value))
				{
					this._ARRIVAL_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AIRLINE_NAME", DbType="VarChar(50)")]
		public string AIRLINE_NAME
		{
			get
			{
				return this._AIRLINE_NAME;
			}
			set
			{
				if ((this._AIRLINE_NAME != value))
				{
					this._AIRLINE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_NAME", DbType="VarChar(50)")]
		public string CLASS_NAME
		{
			get
			{
				return this._CLASS_NAME;
			}
			set
			{
				if ((this._CLASS_NAME != value))
				{
					this._CLASS_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_STATUS_NAME", DbType="VarChar(100)")]
		public string BOOKING_STATUS_NAME
		{
			get
			{
				return this._BOOKING_STATUS_NAME;
			}
			set
			{
				if ((this._BOOKING_STATUS_NAME != value))
				{
					this._BOOKING_STATUS_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIEW_TOUR_HOTEL_DETAIL")]
	public partial class VIEW_TOUR_HOTEL_DETAIL
	{
		
		private int _TOUR_ID;
		
		private string _FROM_DATE;
		
		private string _TO_DATE;
		
		private string _ROOM_TYPE_NAME;
		
		private string _COUNTRY_NAME;
		
		private string _CITY_NAME;
		
		private System.Nullable<int> _NO_OF_ROOMS;
		
		private System.Nullable<decimal> _AMOUNT;
		
		private System.Nullable<decimal> _FINAL_AMOUNT;
		
		private System.Nullable<decimal> _GST;
		
		private string _REMARKS;
		
		private System.Nullable<decimal> _TAX;
		
		private System.Nullable<decimal> _TOTAL_AMOUNT;
		
		private string _HOTEL_NAME;
		
		private string _BOOKING_REQUEST_TO;
		
		private System.Nullable<int> _HOTEL_ID;
		
		private int _SR_NO;
		
		private string _CURRENCY_NAME;
		
		private System.Nullable<int> _ROOM_TO_BE_BLOCKED;
		
		private string _CHECK_REQUEST_DATE;
		
		private string _CHECK_COMMENTS;
		
		private System.Nullable<int> _TOTAL_ROOM_BLOCKED;
		
		private string _TIME_LIMIT;
		
		private string _CHECK_REQUEST_TO;
		
		private string _APPROVED_BY;
		
		private string _BOOKED_BY;
		
		private string _BOOKING_STATUS;
		
		private string _BOOKING_REQUEST_DATE;
		
		private System.Nullable<int> _TOTAL_ROOM_ALLOTEED;
		
		private System.Nullable<int> _PARTIAL_ROOM_ALLOTED;
		
		private System.Nullable<int> _TOTAL_ADULT_ALLOTED;
		
		private System.Nullable<int> _TOTAL_CWB_ALLOTED;
		
		private System.Nullable<int> _TOTAL_CNB_ALLOTED;
		
		private System.Nullable<int> _TOTAL_INFANT_ALLOTED;
		
		private System.Nullable<int> _AVALIBLE_ROOM;
		
		public VIEW_TOUR_HOTEL_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOUR_ID", DbType="Int NOT NULL")]
		public int TOUR_ID
		{
			get
			{
				return this._TOUR_ID;
			}
			set
			{
				if ((this._TOUR_ID != value))
				{
					this._TOUR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_DATE", DbType="VarChar(10)")]
		public string FROM_DATE
		{
			get
			{
				return this._FROM_DATE;
			}
			set
			{
				if ((this._FROM_DATE != value))
				{
					this._FROM_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_DATE", DbType="VarChar(10)")]
		public string TO_DATE
		{
			get
			{
				return this._TO_DATE;
			}
			set
			{
				if ((this._TO_DATE != value))
				{
					this._TO_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_TYPE_NAME", DbType="VarChar(100)")]
		public string ROOM_TYPE_NAME
		{
			get
			{
				return this._ROOM_TYPE_NAME;
			}
			set
			{
				if ((this._ROOM_TYPE_NAME != value))
				{
					this._ROOM_TYPE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_NAME", DbType="VarChar(50)")]
		public string COUNTRY_NAME
		{
			get
			{
				return this._COUNTRY_NAME;
			}
			set
			{
				if ((this._COUNTRY_NAME != value))
				{
					this._COUNTRY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_NAME", DbType="VarChar(50)")]
		public string CITY_NAME
		{
			get
			{
				return this._CITY_NAME;
			}
			set
			{
				if ((this._CITY_NAME != value))
				{
					this._CITY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_ROOMS", DbType="Int")]
		public System.Nullable<int> NO_OF_ROOMS
		{
			get
			{
				return this._NO_OF_ROOMS;
			}
			set
			{
				if ((this._NO_OF_ROOMS != value))
				{
					this._NO_OF_ROOMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				if ((this._AMOUNT != value))
				{
					this._AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINAL_AMOUNT", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> FINAL_AMOUNT
		{
			get
			{
				return this._FINAL_AMOUNT;
			}
			set
			{
				if ((this._FINAL_AMOUNT != value))
				{
					this._FINAL_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GST", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> GST
		{
			get
			{
				return this._GST;
			}
			set
			{
				if ((this._GST != value))
				{
					this._GST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="NVarChar(250)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> TAX
		{
			get
			{
				return this._TAX;
			}
			set
			{
				if ((this._TAX != value))
				{
					this._TAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_AMOUNT", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> TOTAL_AMOUNT
		{
			get
			{
				return this._TOTAL_AMOUNT;
			}
			set
			{
				if ((this._TOTAL_AMOUNT != value))
				{
					this._TOTAL_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEL_NAME", DbType="VarChar(50)")]
		public string HOTEL_NAME
		{
			get
			{
				return this._HOTEL_NAME;
			}
			set
			{
				if ((this._HOTEL_NAME != value))
				{
					this._HOTEL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_REQUEST_TO", DbType="VarChar(101)")]
		public string BOOKING_REQUEST_TO
		{
			get
			{
				return this._BOOKING_REQUEST_TO;
			}
			set
			{
				if ((this._BOOKING_REQUEST_TO != value))
				{
					this._BOOKING_REQUEST_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEL_ID", DbType="Int")]
		public System.Nullable<int> HOTEL_ID
		{
			get
			{
				return this._HOTEL_ID;
			}
			set
			{
				if ((this._HOTEL_ID != value))
				{
					this._HOTEL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SR_NO", DbType="Int NOT NULL")]
		public int SR_NO
		{
			get
			{
				return this._SR_NO;
			}
			set
			{
				if ((this._SR_NO != value))
				{
					this._SR_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCY_NAME", DbType="VarChar(50)")]
		public string CURRENCY_NAME
		{
			get
			{
				return this._CURRENCY_NAME;
			}
			set
			{
				if ((this._CURRENCY_NAME != value))
				{
					this._CURRENCY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_TO_BE_BLOCKED", DbType="Int")]
		public System.Nullable<int> ROOM_TO_BE_BLOCKED
		{
			get
			{
				return this._ROOM_TO_BE_BLOCKED;
			}
			set
			{
				if ((this._ROOM_TO_BE_BLOCKED != value))
				{
					this._ROOM_TO_BE_BLOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_REQUEST_DATE", DbType="VarChar(10)")]
		public string CHECK_REQUEST_DATE
		{
			get
			{
				return this._CHECK_REQUEST_DATE;
			}
			set
			{
				if ((this._CHECK_REQUEST_DATE != value))
				{
					this._CHECK_REQUEST_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_COMMENTS", DbType="VarChar(500)")]
		public string CHECK_COMMENTS
		{
			get
			{
				return this._CHECK_COMMENTS;
			}
			set
			{
				if ((this._CHECK_COMMENTS != value))
				{
					this._CHECK_COMMENTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_ROOM_BLOCKED", DbType="Int")]
		public System.Nullable<int> TOTAL_ROOM_BLOCKED
		{
			get
			{
				return this._TOTAL_ROOM_BLOCKED;
			}
			set
			{
				if ((this._TOTAL_ROOM_BLOCKED != value))
				{
					this._TOTAL_ROOM_BLOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_LIMIT", DbType="VarChar(10)")]
		public string TIME_LIMIT
		{
			get
			{
				return this._TIME_LIMIT;
			}
			set
			{
				if ((this._TIME_LIMIT != value))
				{
					this._TIME_LIMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_REQUEST_TO", DbType="VarChar(101)")]
		public string CHECK_REQUEST_TO
		{
			get
			{
				return this._CHECK_REQUEST_TO;
			}
			set
			{
				if ((this._CHECK_REQUEST_TO != value))
				{
					this._CHECK_REQUEST_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVED_BY", DbType="VarChar(50)")]
		public string APPROVED_BY
		{
			get
			{
				return this._APPROVED_BY;
			}
			set
			{
				if ((this._APPROVED_BY != value))
				{
					this._APPROVED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKED_BY", DbType="VarChar(50)")]
		public string BOOKED_BY
		{
			get
			{
				return this._BOOKED_BY;
			}
			set
			{
				if ((this._BOOKED_BY != value))
				{
					this._BOOKED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_STATUS", DbType="VarChar(100)")]
		public string BOOKING_STATUS
		{
			get
			{
				return this._BOOKING_STATUS;
			}
			set
			{
				if ((this._BOOKING_STATUS != value))
				{
					this._BOOKING_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOKING_REQUEST_DATE", DbType="VarChar(10)")]
		public string BOOKING_REQUEST_DATE
		{
			get
			{
				return this._BOOKING_REQUEST_DATE;
			}
			set
			{
				if ((this._BOOKING_REQUEST_DATE != value))
				{
					this._BOOKING_REQUEST_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_ROOM_ALLOTEED", DbType="Int")]
		public System.Nullable<int> TOTAL_ROOM_ALLOTEED
		{
			get
			{
				return this._TOTAL_ROOM_ALLOTEED;
			}
			set
			{
				if ((this._TOTAL_ROOM_ALLOTEED != value))
				{
					this._TOTAL_ROOM_ALLOTEED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARTIAL_ROOM_ALLOTED", DbType="Int")]
		public System.Nullable<int> PARTIAL_ROOM_ALLOTED
		{
			get
			{
				return this._PARTIAL_ROOM_ALLOTED;
			}
			set
			{
				if ((this._PARTIAL_ROOM_ALLOTED != value))
				{
					this._PARTIAL_ROOM_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_ADULT_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_ADULT_ALLOTED
		{
			get
			{
				return this._TOTAL_ADULT_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_ADULT_ALLOTED != value))
				{
					this._TOTAL_ADULT_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CWB_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_CWB_ALLOTED
		{
			get
			{
				return this._TOTAL_CWB_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_CWB_ALLOTED != value))
				{
					this._TOTAL_CWB_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_CNB_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_CNB_ALLOTED
		{
			get
			{
				return this._TOTAL_CNB_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_CNB_ALLOTED != value))
				{
					this._TOTAL_CNB_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_INFANT_ALLOTED", DbType="Int")]
		public System.Nullable<int> TOTAL_INFANT_ALLOTED
		{
			get
			{
				return this._TOTAL_INFANT_ALLOTED;
			}
			set
			{
				if ((this._TOTAL_INFANT_ALLOTED != value))
				{
					this._TOTAL_INFANT_ALLOTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVALIBLE_ROOM", DbType="Int")]
		public System.Nullable<int> AVALIBLE_ROOM
		{
			get
			{
				return this._AVALIBLE_ROOM;
			}
			set
			{
				if ((this._AVALIBLE_ROOM != value))
				{
					this._AVALIBLE_ROOM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
