<?xml version="1.0" encoding="utf-8"?><Database Name="FULL_CRM_ASHISH" Class="VisaTypeMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVER;Initial Catalog=FULL_CRM_ASHISH;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CRM" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VIEW_COMMON_VISA_TYPE" Member="VIEW_COMMON_VISA_TYPEs">
    <Type Name="VIEW_COMMON_VISA_TYPE">
      <Column Name="VISA_TYPE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VISA_TYPE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>